DEFENV_GETBOOL()
{
	local _val="$1"

	if [ "${_val}" = 0 ]; then
		echo -n 0
	else
		echo -n 1
	fi
}

DEFENV_GETDEF()
{
	local _val="$1" _def="$2"

	if [ -z "${_val}" ] || printf "%s" "${_val}" | grep -Eq '^[[:space:]]+$'; then
		printf "%s" "${_def}"
	else
		printf "%s" "${_val}"
	fi
}

DEFENV_CHKNUMBER()
{
	local _val="$1"

	if printf "%s" "${_val}" | grep -Eq '^[0-9]+$'; then
		return 0
	else
		return 1
	fi
}

PREFIX="${AJ_PREFIX:-${PREFIX}}"
PREFIX=`DEFENV_GETDEF "${PREFIX}" "/usr/local"`

ENABLE_ZFS="${AJ_ENABLE_ZFS:-${ENABLE_ZFS}}"
ENABLE_ZFS=`DEFENV_GETDEF "${ENABLE_ZFS}" 0`
ENABLE_ZFS=`DEFENV_GETBOOL "${ENABLE_ZFS}"`

ZPOOL="${AJ_ZPOOL:-${ZPOOL}}"
ZPOOL=`DEFENV_GETDEF "${ZPOOL}" "zroot"`

ZROOTFS="${AJ_ZROOTFS:-${ZROOTFS}}"
ZROOTFS=`DEFENV_GETDEF "${ZROOTFS}" "appjail"`

ZOPTS="${AJ_ZOPTS:-${ZOPTS}}"
ZOPTS=`DEFENV_GETDEF "${ZOPTS}" "-o compress=lz4"`

SHAREDIR="${AJ_SHAREDIR:-${SHAREDIR}}"
SHAREDIR=`DEFENV_GETDEF "${SHAREDIR}" "${PREFIX}/share/appjail"`

COMMANDS="${AJ_COMMANDS:-${COMMANDS}}"
COMMANDS=`DEFENV_GETDEF "${COMMANDS}" "${SHAREDIR}/share/appjail"`

FILESDIR="${AJ_FILESDIR:-${FILESDIR}}"
FILESDIR=`DEFENV_GETDEF "${FILESDIR}" "${SHAREDIR}/files"`

LIBDIR="${AJ_LIBDIR:-${LIBDIR}}"
LIBDIR=`DEFENV_GETDEF "${LIBDIR}" "${SHAREDIR}/lib"`

SCRIPTSDIR="${AJ_SCRIPTSDIR:-${SCRIPTSDIR}}"
SCRIPTSDIR=`DEFENV_GETDEF "${SCRIPTSDIR}" "${SHAREDIR}/scripts"`

UTILDIR="${AJ_UTILDIR:-${UTILDIR}}"
UTILDIR=`DEFENV_GETDEF "${UTILDIR}" "${SHAREDIR}/util"`

MAKEJAILDIR="${AJ_MAKEJAILDIR:-${MAKEJAILDIR}}"
MAKEJAILDIR=`DEFENV_GETDEF "${MAKEJAILDIR}" "${SHAREDIR}/makejail"`

MAKEJAIL_COMMANDS="${AJ_MAKEJAIL_COMMANDS:-${MAKEJAIL_COMMANDS}}"
MAKEJAIL_COMMANDS=`DEFENV_GETDEF "${MAKEJAILDIR_COMMANDS}" "${MAKEJAILDIR}/cmd"`

MAKEJAIL_WCOMMANDS="${AJ_MAKEJAIL_WCOMMANDS:-${MAKEJAIL_WCOMMANDS}}"
MAKEJAIL_WCOMMANDS=`DEFENV_GETDEF "${MAKEJAIL_WCOMMANDS}" "${MAKEJAILDIR}/write"`

DATADIR="${AJ_DATADIR:-${DATADIR}}"
DATADIR=`DEFENV_GETDEF "${DATADIR}" "${PREFIX}/appjail"`

CACHEDIR="${AJ_CACHEDIR:-${CACHEDIR}}"
CACHEDIR=`DEFENV_GETDEF "${CACHEDIR}" "${CACHEDIR}/cache"`

NETWORKDIR="${AJ_NETWORKDIR:-${NETWORKDIR}}"
NETWORKDIR=`DEFENV_GETDEF "${NETWORKDIR}" "${DATADIR}/networks"`

RELEASEDIR="${AJ_RELEASEDIR:-${RELEASEDIR}}"
RELEASEDIR=`DEFENV_GETDEF "${RELEASEDIR}" "${DATADIR}/releases"`

TMPDIR="${AJ_TMPDIR:-${TMPDIR}}"
TMPDIR=`DEFENV_GETDEF "${TMPDIR}" "${CACHEDIR}/tmp/.appjail"`

GLOBAL_GIT_CACHEDIR="${AJ_GLOBAL_GIT_CACHEDIR:-${GLOBAL_GIT_CACHEDIR}}"
GLOBAL_GIT_CACHEDIR=`DEFENV_GETDEF "${GLOBAL_GIT_CACHEDIR}" "${CACHEDIR}/git"`

COMPONENTSDIR="${AJ_COMPONENTSDIR:-${COMPONENTSDIR}}"
COMPONENTSDIR=`DEFENV_GETDEF "${COMPONENTSDIR}" "${CACHEDIR}/components"`

LOGDIR="${AJ_LOGDIR:-${LOGDIR}}"
LOGDIR=`DEFENV_GETDEF "${LOGDIR}" "/var/log/appjail"`

JAILDIR="${AJ_JAILDIR:-${JAILDIR}}"
JAILDIR=`DEFENV_GETDEF "${JAILDIR}" "${DATADIR}/jails"`

DEFAULT_TEMPLATE="${AJ_DEFAULT_TEMPLATE:-${DEFAULT_TEMPLATE}}"
DEFAULT_TEMPLATE=`DEFENV_GETDEF "${DEFAULT_TEMPLATE}" "${FILESDIR}/default_template.conf"`

DEFAULT_TIMEZONE="${AJ_DEFAULT_TIMEZONE:-${DEFAULT_TIMEZONE}}"

USE_TIMEZONE="${AJ_USE_TIMEZONE:-${USE_TIMEZONE}}"
USE_TIMEZONE=`DEFENV_GETDEF "${USE_TIMEZONE}" 1`
USE_TIMEZONE=`DEFENV_GETBOOL "${USE_TIMEZONE}"`

DEFAULT_BOOT="${AJ_DEFAULT_BOOT:-${DEFAULT_BOOT}}"
DEFAULT_BOOT=`DEFENV_GETDEF "${DEFAULT_BOOT}" 1`
DEFAULT_BOOT=`DEFENV_GETBOOL "${DEFAULT_BOOT}"`

DEFAULT_PRIORITY="${AJ_DEFAULT_PRIORITY:-${DEFAULT_PRIORITY}}"
DEFAULT_PRIORITY=`DEFENV_GETDEF "${DEFAULT_PRIORITY}" 0`

USE_PARALLEL="${AJ_USE_PARALLEL:-${USE_PARALLEL}}"
USE_PARALLEL=`DEFENV_GETDEF "${USE_PARALLEL}" 1`
USE_PARALLEL=`DEFENV_GETBOOL "${USE_PARALLEL}"`

USE_PARALLEL_NATNET="${AJ_USE_PARALLEL_NATNET:-${USE_PARALLEL_NATNET}}"
USE_PARALLEL_NATNET=`DEFENV_GETDEF "${USE_PARALLEL_NATNET}" 1`
USE_PARALLEL_NATNET=`DEFENV_GETBOOL "${USE_PARALLEL_NATNET}"`

DEFAULT_DEVFS_RULESET="${AJ_DEFAULT_DEVFS_RULESET:-${DEFAULT_DEVFS_RULESET}}"
DEFAULT_DEVFS_RULESET=`DEFENV_GETDEF "${DEFAULT_DEVFS_RULESET}" 5`

DEFAULT_MOUNT_DEVFS="${AJ_DEFAULT_MOUNT_DEVFS:-${DEFAULT_MOUNT_DEVFS}}"
DEFAULT_MOUNT_DEVFS=`DEFENV_GETDEF "${DEFAULT_MOUNT_DEVFS}" 0`
DEFAULT_MOUNT_DEVFS=`DEFENV_GETBOOL "${DEFAULT_MOUNT_DEVFS}"`

DEFAULT_START="${AJ_DEFAULT_START:-${DEFAULT_START}}"
DEFAULT_START=`DEFENV_GETDEF "${DEFAULT_START}" 0`
DEFAULT_START=`DEFENV_GETBOOL "${DEFAULT_START}"`

DEFAULT_RESTART="${AJ_DEFAULT_RESTART:-${DEFAULT_RESTART}}"
DEFAULT_RESTART=`DEFENV_GETDEF "${DEFAULT_RESTART}" 0`
DEFAULT_RESTART=`DEFENV_GETBOOL "${DEFAULT_RESTART}"`

DEFAULT_RUN="${AJ_DEFAULT_RUN:-${DEFAULT_RUN}}"
DEFAULT_RUN=`DEFENV_GETDEF "${DEFAULT_RUN}" 0`
DEFAULT_RUN=`DEFENV_GETBOOL "${DEFAULT_RUN}"`

DEFAULT_LOGIN="${AJ_DEFAULT_LOGIN:-${DEFAULT_LOGIN}}"
DEFAULT_LOGIN=`DEFENV_GETDEF "${DEFAULT_LOGIN}" 0`
DEFAULT_LOGIN=`DEFENV_GETBOOL "${DEFAULT_LOGIN}"`

DEFAULT_LOGIN_USER="${AJ_DEFAULT_LOGIN_USER:-${DEFAULT_LOGIN_USER}}"
DEFAULT_LOGIN_USER=`DEFENV_GETDEF "${DEFAULT_LOGIN_USER}" "root"`

DEFAULT_COPYDIR="${AJ_DEFAULT_COPYDIR:-${DEFAULT_COPYDIR}}"
DEFAULT_COPYDIR=`DEFENV_GETDEF "${DEFAULT_COPYDIR}" "/"`

DEFAULT_OVERWRITE="${AJ_DEFAULT_OVERWRITE:-${DEFAULT_OVERWRITE}}"
DEFAULT_OVERWRITE=`DEFENV_GETDEF "${DEFAULT_OVERWRITE}" 0`
DEFAULT_OVERWRITE=`DEFENV_GETBOOL "${DEFAULT_OVERWRITE}"`

HOST_DOMAIN="${AJ_HOST_DOMAIN:-${HOST_DOMAIN}}"
HOST_DOMAIN=`DEFENV_GETDEF "${HOST_DOMAIN}" ".appjail"`

USE_FIREWALL="${AJ_USE_FIREWALL:-${USE_FIREWALL}}"
USE_FIREWALL=`DEFENV_GETDEF "${USE_FIREWALL}" "pf"`

EXT_IF="${AJ_EXT_IF:-${EXT_IF}}"
EXT_IF=`DEFENV_GETDEF "${EXT_IF}" ""`
if [ -z "${EXT_IF}" ]; then
	# Get the external interface from the IPv4 routes.
	EXT_IF=`route -4 get default 2> /dev/null | grep 'interface:' | cut -d' ' -f4-`

	# If not, try to get the external interface from the IPv6 routes.
	if [ -z "${EXT_IF}" ]; then
		EXT_IF=`route -6 get default 2> /dev/null | grep 'interface:' | cut -d' ' -f4-`
	fi

	if [ -z "${EXT_IF}" ]; then
		echo "The external interface is not configured!" >&2
		exit 78 # EX_CONFIG
	fi
fi

ON_IF="${AJ_ON_IF:-${ON_IF}}"
ON_IF=`DEFENV_GETDEF "${ON_IF}" "${EXT_IF}"`

SHARED_BRIDGE="${AJ_SHARED_BRIDGE:-${SHARED_BRIDGE}}"
SHARED_BRIDGE=`DEFENV_GETDEF "${SHARED_BRIDGE}" "appjail"`

DEFAULT_MTU="${AJ_DEFAULT_MTU:-${DEFAULT_MTU}}"
DEFAULT_MTU=`DEFENV_GETDEF "${DEFAULT_MTU}" 1500`
if ! DEFENV_CHKNUMBER "${DEFAULT_MTU}"; then
	echo "Invalid MTU: ${DEFAULT_MTU}" >&2
	exit 78 # EX_CONFIG
fi

DEFAULT_RESOLV_CONF="${AJ_DEFAULT_RESOLV_CONF:-${DEFAULT_RESOLV_CONF}}"
DEFAULT_RESOLV_CONF=`DEFENV_GETDEF "${DEFAULT_RESOLV_CONF}" "/etc/resolv.conf"`

USE_RESOLV_CONF="${AJ_USE_RESOLV_CONF:-${USE_RESOLV_CONF}}"
USE_RESOLV_CONF=`DEFENV_GETDEF "${USE_RESOLV_CONF}" 1`
USE_RESOLV_CONF=`DEFENV_GETBOOL "${USE_RESOLV_CONF}"`

CREATED_FORMAT="${AJ_CREATED_FORMAT:-${CREATED_FORMAT}}"
CREATED_FORMAT=`DEFENV_GETDEF "${CREATED_FORMAT}" "%Y-%m-%d %H:%M:%S"`

CONSOLELOG_NAME="${AJ_CONSOLELOG_NAME:-${CONSOLELOG_NAME}}"
CONSOLELOG_NAME=`DEFENV_GETDEF "${CONSOLELOG_NAME}" "date +%Y-%m-%d.log"`

SESSION_ID_NAME="${AJ_SESSION_ID_NAME:-${SESSION_ID_NAME}}"
SESSION_ID_NAME=`DEFENV_GETDEF "${SESSION_ID_NAME}" "date +%Y-%m-%d.log"`

STARTUPLOG_NAME="${AJ_STARTUPLOG_NAME:-${STARTUPLOG_NAME}}"
STARTUPLOG_NAME=`DEFENV_GETDEF "${STARTUPLOG_NAME}" "date +%Y-%m-%d.log"`

FREEBSD_UPDATE_CONF="${AJ_FREEBSD_UPDATE_CONF:-${FREEBSD_UPDATE_CONF}}"
FREEBSD_UPDATE_CONF=`DEFENV_GETDEF "${FREEBSD_UPDATE_CONF}" "/etc/freebsd-update.conf"`

DEFAULT_FETCH_METHOD="${AJ_DEFAULT_FETCH_METHOD:-${DEFAULT_FETCH_METHOD}}"
DEFAULT_FETCH_METHOD=`DEFENV_GETDEF "${DEFAULT_FETCH_METHOD}" "www"`

DEFAULT_INSTALL_METHOD="${AJ_DEFAULT_INSTALL_METHOD:-${DEFAULT_INSTALL_METHOD}}"
DEFAULT_INSTALL_METHOD=`DEFENV_GETDEF "${DEFAULT_INSTALL_METHOD}" "standard"`

DOWNLOADURL="${AJ_DOWNLOADURL:-${DOWNLOADURL}}"
DOWNLOADURL=`DEFENV_GETDEF "${DOWNLOADURL}" "https://download.freebsd.org/releases/%a/%v"`

COMPONENTS="${AJ_COMPONENTS:-${COMPONENTS}}"
COMPONENTS=`DEFENV_GETDEF "${COMPONENTS}" "base.txz"`

DEFAULT_RELEASE="${AJ_DEFAULT_RELEASE:-${DEFAULT_RELEASE}}"
DEFAULT_RELEASE=`DEFENV_GETDEF "${DEFAULT_RELEASE}" "default"`

WWW_CMD="${AJ_WWW_CMD:-${WWW_CMD}}"
WWW_CMD=`DEFENV_GETDEF "${WWW_CMD}" "fetch -Rpm -o %o %u/%c"`

MAKEJAIL_FETCH_CMD="${AJ_MAKEJAIL_FETCH_CMD:-${MAKEJAIL_FETCH_CMD}}"
MAKEJAIL_FETCH_CMD=`DEFENV_GETDEF "${MAKEJAIL_FETCH_CMD}" "fetch -Rpm -o %o %u"`

MAKEJAIL_ADD_FETCH_CMD="${AJ_MAKEJAIL_ADD_FETCH_CMD:-${MAKEJAIL_ADD_FETCH_CMD}}"
MAKEJAIL_ADD_FETCH_CMD=`DEFENV_GETDEF "${MAKEJAIL_ADD_FETCH_CMD}" "fetch -Rpm -o - %u"`

FREEBSD_ARCH="${AJ_FREEBSD_ARCH:-${FREEBSD_ARCH}}"
FREEBSD_ARCH=`DEFENV_GETDEF "${FREEBSD_ARCH}" ""`
if [ -z "${FREEBSD_ARCH}" ]; then
	FREEBSD_ARCH=`uname -m`
fi

FREEBSD_VERSION="${AJ_FREEBSD_VERSION:-${FREEBSD_VERSION}}"
FREEBSD_VERSION=`DEFENV_GETDEF "${FREEBSD_VERSION}" ""`
if [ -z "${FREEBSD_VERSION}" ]; then
	FREEBSD_VERSION=`freebsd-version | grep -Eo '[0-9]+\.[0-9]+-[a-zA-Z0-9]+'`
fi

DEBOOTSTRAP_CMD="${AJ_DEBOOTSTRAP_CMD:-${DEBOOTSTRAP_CMD}}"
DEBOOTSTRAP_CMD=`DEFENV_GETDEF "${DEBOOTSTRAP_CMD}" "debootstrap --foreign --arch=%a --no-check-gpg %s %o"`

DEBOOTSTRAP_ARCH="${AJ_DEBOOTSTRAP_ARCH:-${DEBOOTSTRAP_ARCH}}"
DEBOOTSTRAP_ARCH=`DEFENV_GETDEF "${DEBOOTSTRAP_ARCH}" "${FREEBSD_ARCH}"`

DEBOOTSTRAP_MIRROR="${AJ_DEBOOTSTRAP_MIRROR:-${DEBOOTSTRAP_MIRROR}}"

DEBOOTSTRAP_SCRIPT="${AJ_DEBOOTSTRAP_SCRIPT:-${DEBOOTSTRAP_SCRIPT}}"

APT_CACHE_START="${AJ_APT_CACHE_START:-${APT_CACHE_START}}"
APT_CACHE_START=`DEFENV_GETDEF "${APT_CACHE_START}" "251658240"`
if ! DEFENV_CHKNUMBER "${APT_CACHE_START}"; then
	echo "Invalid number (APT_CACHE_START): ${APT_CACHE_START}" >&2
	exit 78 # EX_CONFIG
fi

ENABLE_DEBUG="${AJ_ENABLE_DEBUG:-${ENABLE_DEBUG}}"
ENABLE_DEBUG=`DEFENV_GETDEF "${ENABLE_DEBUG}" 1`
ENABLE_DEBUG=`DEFENV_GETBOOL "${ENABLE_DEBUG}"`

ENABLE_COLORS="${AJ_ENABLE_COLORS:-${ENABLE_COLORS}}"
ENABLE_COLORS=`DEFENV_GETDEF "${ENABLE_COLORS}" 1`
ENABLE_COLORS=`DEFENV_GETBOOL "${ENABLE_COLORS}"`

ENABLE_RANDOM_COLORS="${AJ_ENABLE_RANDOM_COLORS:-${ENABLE_RANDOM_COLORS}}"
ENABLE_RANDOM_COLORS=`DEFENV_GETDEF "${ENABLE_RANDOM_COLORS}" 1`
ENABLE_RANDOM_COLORS=`DEFENV_GETBOOL "${ENABLE_RANDOM_COLORS}"`

ENABLE_LOGGING_OUTPUT="${AJ_ENABLE_LOGGING_OUTPUT:-${ENABLE_LOGGING_OUTPUT}}"
ENABLE_LOGGING_OUTPUT=`DEFENV_GETDEF "${ENABLE_LOGGING_OUTPUT}" 0`
ENABLE_LOGGING_OUTPUT=`DEFENV_GETBOOL "${ENABLE_LOGGING_OUTPUT}"`

SCRIPT_TIME="${AJ_SCRIPT_TIME:-${SCRIPT_TIME}}"
SCRIPT_TIME=`DEFENV_GETDEF "${SCRIPT_TIME}" 30`
if ! DEFENV_CHKNUMBER "${SCRIPT_TIME}"; then
	echo "Invalid number (SCRIPT_TIME): ${SCRIPT_TIME}" >&2
	exit 78 # EX_CONFIG
fi


TAR_ARGS="${AJ_TAR_ARGS:-${TAR_ARGS}}"

TAR_COMPRESS_ARGS="${AJ_TAR_COMPRESS_ARGS:-${TAR_COMPRESS_ARGS}}"
TAR_COMPRESS_ARGS=`DEFENV_GETDEF "${TAR_COMPRESS_ARGS}" "${TAR_ARGS}"`

TAR_DECOMPRESS_ARGS="${AJ_TAR_DECOMPRESS_ARGS:-${TAR_DECOMPRESS_ARGS}}"
TAR_DECOMPRESS_ARGS=`DEFENV_GETDEF "${TAR_DECOMPRESS_ARGS}" "${TAR_ARGS}"`

TAR_BZIP_ARGS="${AJ_TAR_BZIP_ARGS:-${TAR_BZIP_ARGS}}"
TAR_BZIP_ARGS=`DEFENV_GETDEF "${TAR_BZIP_ARGS}" "${TAR_COMPRESS_ARGS} --bzip"`

TAR_GZIP_ARGS="${AJ_TAR_GZIP_ARGS:-${TAR_GZIP_ARGS}}"
TAR_GZIP_ARGS=`DEFENV_GETDEF "${TAR_GZIP_ARGS}" "${TAR_COMPRESS_ARGS} --gzip"`

TAR_LRZIP_ARGS="${AJ_TAR_LRZIP_ARGS:-${TAR_LRZIP_ARGS}}"
TAR_LRZIP_ARGS=`DEFENV_GETDEF "${TAR_LRZIP_ARGS}" "${TAR_COMPRESS_ARGS} --lrzip"`

TAR_LZ4_ARGS="${AJ_TAR_LZ4_ARGS:-${TAR_LZ4_ARGS}}"
TAR_LZ4_ARGS=`DEFENV_GETDEF "${TAR_LZ4_ARGS}" "${TAR_COMPRESS_ARGS} --lz4"`

TAR_LZMA_ARGS="${AJ_TAR_LZMA_ARGS:-${TAR_LZMA_ARGS}}"
TAR_LZMA_ARGS=`DEFENV_GETDEF "${TAR_LZMA_ARGS}" "${TAR_COMPRESS_ARGS} --lzma"`

TAR_LZOP_ARGS="${AJ_TAR_LZOP_ARGS:-${TAR_LZOP_ARGS}}"
TAR_LZOP_ARGS=`DEFENV_GETDEF "${TAR_LZOP_ARGS}" "${TAR_COMPRESS_ARGS} --lzop"`

TAR_XZ_ARGS="${AJ_TAR_XZ_ARGS:-${TAR_XZ_ARGS}}"
TAR_XZ_ARGS=`DEFENV_GETDEF "${TAR_XZ_ARGS}" "${TAR_COMPRESS_ARGS} --xz"`

TAR_ZSTD_ARGS="${AJ_TAR_ZSTD_ARGS:-${TAR_ZSTD_ARGS}}"
TAR_ZSTD_ARGS=`DEFENV_GETDEF "${TAR_ZSTD_ARGS}" "${TAR_COMPRESS_ARGS} --zstd"`


BZIP_ARGS="${AJ_BZIP_ARGS:-${BZIP_ARGS}}"

BZIP_COMPRESS_ARGS="${AJ_BZIP_COMPRESS_ARGS:-${BZIP_COMPRESS_ARGS}}"
BZIP_COMPRESS_ARGS=`DEFENV_GETDEF "${BZIP_COMPRESS_ARGS}" "${BZIP_ARGS}"`

BZIP_COMPRESS_CMD="${AJ_BZIP_COMPRESS_CMD:-${BZIP_COMPRESS_CMD}}"
BZIP_COMPRESS_CMD=`DEFENV_GETDEF "${BZIP_COMPRESS_CMD}" "bzip2 ${BZIP_COMPRESS_ARGS}"`

BZIP_DECOMPRESS_ARGS="${AJ_BZIP_DECOMPRESS_ARGS:-${BZIP_DECOMPRESS_ARGS}}"
BZIP_DECOMPRESS_ARGS=`DEFENV_GETDEF "${BZIP_DECOMPRESS_ARGS}" "${BZIP_ARGS}"`

BZIP_DECOMPRESS_CMD="${AJ_BZIP_DECOMPRESS_CMD:-${BZIP_DECOMPRESS_CMD}}"
BZIP_DECOMPRESS_CMD=`DEFENV_GETDEF "${BZIP_DECOMPRESS_CMD}" "bzip2 ${BZIP_DECOMPRESS_ARGS} -d"`


GZIP_ARGS="${AJ_GZIP_ARGS:-${GZIP_ARGS}}"

GZIP_COMPRESS_ARGS="${AJ_GZIP_COMPRESS_ARGS:-${GZIP_COMPRESS_ARGS}}"
GZIP_COMPRESS_ARGS=`DEFENV_GETDEF "${GZIP_COMPRESS_ARGS}" "${GZIP_ARGS}"`

GZIP_COMPRESS_CMD="${AJ_GZIP_COMPRESS_CMD:-${GZIP_COMPRESS_CMD}}"
GZIP_COMPRESS_CMD=`DEFENV_GETDEF "${GZIP_COMPRESS_CMD}" "gzip ${GZIP_COMPRESS_ARGS}"`

GZIP_DECOMPRESS_ARGS="${AJ_GZIP_DECOMPRESS_ARGS:-${GZIP_DECOMPRESS_ARGS}}"
GZIP_DECOMPRESS_ARGS=`DEFENV_GETDEF "${GZIP_DECOMPRESS_ARGS}" "${GZIP_ARGS}"`

GZIP_DECOMPRESS_CMD="${AJ_GZIP_DECOMPRESS_CMD:-${GZIP_DECOMPRESS_CMD}}"
GZIP_DECOMPRESS_CMD=`DEFENV_GETDEF "${GZIP_DECOMPRESS_CMD}" "gzip -d ${GZIP_DECOMPRESS_ARGS}"`


LRZIP_ARGS="${AJ_LRZIP_ARGS:-${LRZIP_ARGS}}"

LRZIP_COMPRESS_ARGS="${AJ_LRZIP_COMPRESS_ARGS:-${LRZIP_COMPRESS_ARGS}}"
LRZIP_COMPRESS_ARGS=`DEFENV_GETDEF "${LRZIP_COMPRESS_ARGS}" "${LRZIP_ARGS}"`

LRZIP_COMPRESS_CMD="${AJ_LRZIP_COMPRESS_CMD:-${LRZIP_COMPRESS_CMD}}"
LRZIP_COMPRESS_CMD=`DEFENV_GETDEF "${LRZIP_COMPRESS_CMD}" "lrzip ${LRZIP_COMPRESS_ARGS}"`

LRZIP_DECOMPRESS_ARGS="${AJ_LRZIP_DECOMPRESS_ARGS:-${LRZIP_DECOMPRESS_ARGS}}"
LRZIP_DECOMPRESS_ARGS=`DEFENV_GETDEF "${LRZIP_DECOMPRESS_ARGS}" "${LRZIP_ARGS}"`

LRZIP_DECOMPRESS_CMD="${AJ_LRZIP_DECOMPRESS_CMD:-${LRZIP_DECOMPRESS_CMD}}"
LRZIP_DECOMPRESS_CMD=`DEFENV_GETDEF "${LRZIP_DECOMPRESS_CMD}" "lrzip -d ${LRZIP_DECOMPRESS_ARGS}"`


LZ4_ARGS="${AJ_LZ4_ARGS:-${LZ4_ARGS}}"

LZ4_COMPRESS_ARGS="${AJ_LZ4_COMPRESS_ARGS:-${LZ4_COMPRESS_ARGS}}"
LZ4_COMPRESS_ARGS=`DEFENV_GETDEF "${LZ4_COMPRESS_ARGS}" "${LZ4_ARGS}"`

LZ4_COMPRESS_CMD="${AJ_LZ4_COMPRESS_CMD:-${LZ4_COMPRESS_CMD}}"
LZ4_COMPRESS_CMD=`DEFENV_GETDEF "${LZ4_COMPRESS_CMD}" "lz4 ${LZ4_COMPRESS_ARGS}"`

LZ4_DECOMPRESS_ARGS="${AJ_LZ4_DECOMPRESS_ARGS:-${LZ4_DECOMPRESS_ARGS}}"
LZ4_DECOMPRESS_ARGS=`DEFENV_GETDEF "${LZ4_DECOMPRESS_ARGS}" "${LZ4_ARGS}"`

LZ4_DECOMPRESS_CMD="${AJ_LZ4_DECOMPRESS_CMD:-${LZ4_DECOMPRESS_CMD}}"
LZ4_DECOMPRESS_CMD=`DEFENV_GETDEF "${LZ4_DECOMPRESS_CMD}" "lz4 -d ${LZ4_DECOMPRESS_ARGS}"`


LZMA_ARGS="${AJ_LZMA_ARGS:-${LZMA_ARGS}}"

LZMA_COMPRESS_ARGS="${AJ_LZMA_COMPRESS_ARGS:-${LZMA_COMPRESS_ARGS}}"
LZMA_COMPRESS_ARGS=`DEFENV_GETDEF "${LZMA_COMPRESS_ARGS}" "${LZMA_ARGS}"`

LZMA_COMPRESS_CMD="${AJ_LZMA_COMPRESS_CMD:-${LZMA_COMPRESS_CMD}}"
LZMA_COMPRESS_CMD=`DEFENV_GETDEF "${LZMA_COMPRESS_CMD}" "lzma ${LZMA_COMPRESS_ARGS}"`

LZMA_DECOMPRESS_ARGS="${AJ_LZMA_DECOMPRESS_ARGS:-${LZMA_DECOMPRESS_ARGS}}"
LZMA_DECOMPRESS_ARGS=`DEFENV_GETDEF "${LZMA_DECOMPRESS_ARGS}" "${LZMA_ARGS}"`

LZMA_DECOMPRESS_CMD="${LZMA_DECOMPRESS_CMD:-${LZMA_DECOMPRESS_CMD}}"
LZMA_DECOMPRESS_CMD=`DEFENV_GETDEF "${LZMA_DECOMPRESS_CMD}" "lzma -d ${LZMA_DECOMPRESS_ARGS}"`


LZOP_ARGS="${AJ_LZOP_ARGS:-${LZOP_ARGS}}"

LZOP_COMPRESS_ARGS="${AJ_LZOP_COMPRESS_ARGS:-${LZOP_COMPRESS_ARGS}}"
LZOP_COMPRESS_ARGS=`DEFENV_GETDEF "${LZOP_COMPRESS_ARGS}" "${LZOP_ARGS}"`

LZOP_COMPRESS_CMD="${AJ_LZOP_COMPRESS_CMD:-${LZOP_COMPRESS_CMD}}"
LZOP_COMPRESS_CMD=`DEFENV_GETDEF "${LZOP_COMPRESS_CMD}" "lzop ${LZOP_COMPRESS_ARGS}"`

LZOP_DECOMPRESS_ARGS="${AJ_LZOP_DECOMPRESS_ARGS:-${LZOP_DECOMPRESS_ARGS}}"
LZOP_DECOMPRESS_ARGS=`DEFENV_GETDEF "${LZOP_DECOMPRESS_ARGS}" "${LZOP_ARGS}"`

LZOP_DECOMPRESS_CMD="${AJ_LZOP_DECOMPRESS_CMD:-${LZOP_DECOMPRESS_CMD}}"
LZOP_DECOMPRESS_CMD=`DEFENV_GETDEF "${LZOP_DECOMPRESS_CMD}" "lzop -d ${LZOP_DECOMPRESS_ARGS}"`


XZ_ARGS="${AJ_XZ_ARGS:-${XZ_ARGS}}"

XZ_COMPRESS_ARGS="${AJ_XZ_COMPRESS_ARGS:-${XZ_COMPRESS_ARGS}}"
XZ_COMPRESS_ARGS=`DEFENV_GETDEF "${XZ_COMPRESS_ARGS}" "${XZ_ARGS}"`

XZ_COMPRESS_CMD="${AJ_XZ_COMPRESS_CMD:-${XZ_COMPRESS_CMD}}"
XZ_COMPRESS_CMD=`DEFENV_GETDEF "${XZ_COMPRESS_CMD}" "xz ${XZ_COMPRESS_ARGS}"`

XZ_DECOMPRESS_ARGS="${AJ_XZ_DECOMPRESS_ARGS:-${XZ_DECOMPRESS_ARGS}}"
XZ_DECOMPRESS_ARGS=`DEFENV_GETDEF "${XZ_DECOMPRESS_ARGS}" "${XZ_ARGS}"`

XZ_DECOMPRESS_CMD="${AJ_XZ_DECOMPRESS_CMD:-${XZ_DECOMPRESS_CMD}}"
XZ_DECOMPRESS_CMD=`DEFENV_GETDEF "${XZ_DECOMPRESS_CMD}" "xz -d ${XZ_DECOMPRESS_ARGS}"`


ZSTD_ARGS="${AJ_ZSTD_ARGS:-${ZSTD_ARGS}}"

ZSTD_COMPRESS_ARGS="${AJ_ZSTD_COMPRESS_ARGS:-${ZSTD_COMPRESS_ARGS}}"
ZSTD_COMPRESS_ARGS=`DEFENV_GETDEF "${ZSTD_COMPRESS_ARGS}" "${ZSTD_ARGS}"`

ZSTD_COMPRESS_CMD="${AJ_ZSTD_COMPRESS_CMD:-${ZSTD_COMPRESS_CMD}}"
ZSTD_COMPRESS_CMD=`DEFENV_GETDEF "${ZSTD_COMPRESS_CMD}" "zstd ${ZSTD_COMPRESS_ARGS}"`

ZSTD_DECOMPRESS_ARGS="${AJ_ZSTD_DECOMPRESS_ARGS:-${ZSTD_DECOMPRESS_ARGS}}"
ZSTD_DECOMPRESS_ARGS=`DEFENV_GETDEF "${ZSTD_DECOMPRESS_ARGS}" "${ZSTD_ARGS}"`

ZSTD_DECOMPRESS_CMD="${ZSTD_DECOMPRESS_CMD:-${ZSTD_DECOMPRESS_CMD}}"
ZSTD_DECOMPRESS_CMD=`DEFENV_GETDEF "${ZSTD_DECOMPRESS_CMD}" "zstd -d ${ZSTD_DECOMPRESS_ARGS}"`


unset -f DEFENV_GETBOOL
unset -f DEFENV_GETDEF
unset -f DEFENV_CHKNUMBER
