#!/bin/sh
#
# Copyright (c) 2022, Jesús Daniel Colmenares Oviedo <DtxdF@disroot.org>
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

clean_desc="Remove an incomplete or dirty Appjail installation."

clean_main()
{
	. "${LIBDIR}/replace"
	. "${LIBDIR}/su"

	lib_debug "Cleaning..."

	clean_appjails -c "${CONFIG}"
}

clean_appjails()
{
	lib_su /bin/sh "${SCRIPTSDIR}/clean.sh" $@
}

clean_help()
{
	clean_usage

	echo
	echo "${clean_desc}"
	echo
	echo "Any event can lead to incomplete or dirty appjails. This is useless, so removing"
	echo "such things with this command is very useful. Of course, you can try to fix the"
	echo "missing files, but it is much easier to reinstall the appjail application instead"
	echo "of becoming Sherlock Holmes."
}

clean_usage()
{
	echo "usage: clean"
}
