#!/bin/sh
#
# Copyright (c) 2022-2023, Jesús Daniel Colmenares Oviedo <DtxdF@disroot.org>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
# * Neither the name of the copyright holder nor the names of its
#   contributors may be used to endorse or promote products derived from
#   this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

lib_load "${LIBDIR}/check_func"
lib_load "${LIBDIR}/colors"
lib_load "${LIBDIR}/random"
lib_load "${LIBDIR}/replace"

enable_desc="Enable a parameter."

enable_main()
{
	local _o
	local jail_path
	local bootdir
	local jail_name="$1"
	local command="$2"

	shift 2

	if lib_check_empty "${jail_name}" || lib_check_empty "${command}"; then
		enable_usage
		exit ${EX_USAGE}
	fi

	if ! lib_check_jailname "${jail_name}"; then
		lib_err ${EX_DATAERR} "Invalid jail name \"${jail_name}\""
	fi

	if [ $# -eq 0 ]; then
		enable_usage
		exit ${EX_USAGE}
	fi

	lib_set_logprefix " [`random_color`${jail_name}${COLOR_DEFAULT}]"

	jail_path="${JAILDIR}/${jail_name}"
	if [ ! -d "${jail_path}/jail" ]; then
		lib_err ${EX_NOINPUT} "Cannot find the jail \`${jail_name}\`"
	fi

	case "${command}" in
		start|stop|run) ;;
		*) enable_usage; exit ${EX_USAGE} ;;
	esac

	bootdir="${jail_path}/conf/boot/${command}"
	if ! mkdir -p "${bootdir}"; then
		lib_err ${EX_SOFTWARE} "Error creating ${bootdir}."
	fi

	case "${command}" in
		start)
			enable_start "${jail_name}" "$@"
			;;
		stop)
			enable_stop "${jail_name}" "$@"
			;;
		run)
			enable_run "${jail_name}" "$@"
			;;
	esac
}

enable_start()
{
	local _o
	local jail_name
	local jail_path
	local bootdir
	local opt_run_initscript=1
	local create_args=
	local initscript=
	local start_args=
	local template=

	if [ $# -eq 0 ]; then
		lib_err ${EX_USAGE} "usage: enable_start jail_name [-I | [[-c parameter=value ...]] [-i initscript] [[-s parameter=value ...]]] [-t template]"
	fi

	jail_name="$1"; shift
	if [ -z "${jail_name}" ]; then
		enable_start # usage
	fi

	jail_path="${JAILDIR}/${jail_name}"
	bootdir="${jail_path}/conf/boot/start"

	while getopts "Ic:i:s:t:" _o; do
		case "${_o}" in
			I)
				opt_run_initscript=0
				;;
			c)
				local arg="${OPTARG}"
				arg=`lib_escape_string "${arg}" "" '\"' "-"`

				create_args="${create_args} \"${arg}\""
				;;
			i)
				initscript="${OPTARG}"
				;;
			s)
				local arg="${OPTARG}"
				arg=`lib_escape_string "${arg}" "" '\"' "-"`

				start_args="${start_args} \"${arg}\""
				;;
			t)
				template="${OPTARG}"
				;;
			*)
				lib_err ${EX_DATAERR} "Invalid option -- ${OPTARG}"
				;;
		esac
	done

	if [ ${opt_run_initscript} -eq 0 ]; then
		touch "${bootdir}/norun_initscript"
	fi

	if ! lib_check_empty "${create_args}"; then
		printf "%s\n" "${create_args}" > "${bootdir}/create_args" || exit ${EX_IOERR}
	fi

	if ! lib_check_empty "${initscript}"; then
		printf "%s\n" "${initscript}" > "${bootdir}/initscript" || exit ${EX_IOERR}
	fi

	if ! lib_check_empty "${start_args}"; then
		printf "%s\n" "${start_args}" > "${bootdir}/start_args" || exit ${EX_IOERR}
	fi

	if ! lib_check_empty "${template}"; then
		printf "%s\n" "${template}" > "${bootdir}/template" || exit ${EX_IOERR}
	fi
}

enable_stop()
{
	local _o
	local jail_name
	local jail_path
	local bootdir
	local opt_run_initscript=1
	local initscript=
	local args=

	if [ $# -eq 0 ]; then
		lib_err ${EX_USAGE} "usage: enable_stop jail_name [-I | [-i initscript] [[-p parameter=value ...]]]"
	fi

	jail_name="$1"; shift
	if [ -z "${jail_name}" ]; then
		enable_stop # usage
	fi

	jail_path="${JAILDIR}/${jail_name}"
	bootdir="${jail_path}/conf/boot/stop"

	while getopts ":Ii:p:" _o; do
		case "${_o}" in
			I)
				opt_run_initscript=0
				;;
			i)
				initscript="${OPTARG}"
				;;
			p)
				local arg="${OPTARG}"
				arg=`lib_escape_string "${arg}" "" '\"' "-"`

				args="${args} \"${arg}\""
				;;
			*)
				lib_err ${EX_DATAERR} "Invalid option -- ${OPTARG}"
				;;
		esac
	done

	if [ ${opt_run_initscript} -eq 0 ]; then
		touch "${bootdir}/norun_initscript"
	fi

	if ! lib_check_empty "${initscript}"; then
		printf "%s\n" "${initscript}" > "${bootdir}/initscript" || exit ${EX_IOERR}
	fi

	if ! lib_check_empty "${args}"; then
		printf "%s\n" "${args}" > "${bootdir}/args" || exit ${EX_IOERR}
	fi
}

enable_run()
{
	local _o
	local jail_name
	local jail_path
	local bootdir
	local initscript=
	local args=

	if [ $# -eq 0 ]; then
		lib_err ${EX_USAGE} "usage: enable_run jail_name [-i initscript] [[-p parameter=value ...]]"
	fi

	jail_name="$1"; shift
	if [ -z "${jail_name}" ]; then
		enable_run # usage
	fi

	jail_path="${JAILDIR}/${jail_name}"
	bootdir="${jail_path}/conf/boot/run"

	while getopts ":i:p:" _o; do
		case "${_o}" in
			i)
				initscript="${OPTARG}"
				;;
			p)
				local arg="${OPTARG}"
				arg=`lib_escape_string "${arg}" "" '\"' "-"`

				args="${args} \"${arg}\""
				;;
			*)
				lib_err ${EX_DATAERR} "Invalid option -- ${OPTARG}"
				;;
		esac
	done

	if ! lib_check_empty "${initscript}"; then
		printf "%s\n" "${initscript}" > "${bootdir}/initscript" || exit ${EX_IOERR}
	fi

	if ! lib_check_empty "${args}"; then
		printf "%s\n" "${args}" > "${bootdir}/args" || exit ${EX_IOERR}
	fi
}

enable_help()
{
	cat << EOF
`enable_usage`

${enable_desc}

Parameters:
    start                     -- Enable parameters for the start command.
    stop                      -- Enable parameters for the stop command.
    run                       -- Enable parameters for the run command.

Options for start:
    -I                        -- Don't run the initscript.
    -c parameter=value        -- Parameters for *create functions.
    -i initscript             -- Use a custom initscript.
    -s parameter=value        -- Parameters for *start functions.
    -t template               -- Use a custom template.

Options for stop:
    -I                        -- Don't run the initscript.
    -i initscript             -- Use a custom initscript.
    -p parameter=value        -- Parameters for *stop functions.

Options for run:
    -i initscript             -- Use a custom initscript.
    -p parameter=value        -- Parameters for *cmd functions.
EOF
}

enable_usage()
{
	cat << EOF
usage: enable jail start [-I | [[-c parameter=value ...]] [-i initscript] [[-s parameter=value ...]]] [-t template]
       enable jail stop [-I | [-i initscript] [[-p parameter=value ...]]]
       enable jail run [-i initscript] [[-p parameter=value ...]]
EOF
}
