#!/bin/sh

getdir_desc="Get working directory of templates, jails and appjails"

getdir_main()
{
	local _o

	if [ $# -eq 0 ]; then
		getdir_usage
		exit ${EX_USAGE}
	fi
	
	. "${LIBDIR}/replace"

	while getopts ":ajt" _o; do
		case "${_o}" in
			a)
				echo "${APPSDIR}"; exit
				;;
			j)
				lib_replace_jaildir
				echo "${JAILDIR}"; exit
				;;
			t)
				echo "${TEMPLATES}"; exit
				;;
			*)
				getdir_usage
				exit ${EX_USAGE}
				;;
		esac
	done
}

getdir_help()
{
	getdir_usage

	echo
	echo "${getdir_desc}"
	echo
	echo "This command is very useful for scripting. You can use ls(1), cat(1) or any program"
	echo "you want. For example, you can run 'ls \"\`appjail getdir -j\`/foo\"' to list the"
	echo "foo jail. Perhaps you may need to run the command as root."
	echo
	echo "  -a        Show the appjails directory."
	echo "  -j        Show the jails directory."
	echo "  -t        Show the templates directory."
}

getdir_usage()
{
	echo "usage: getdir [-a | -j | -t]"
}
