#!/bin/sh
#
# Copyright (c) 2022, Jesús Daniel Colmenares Oviedo <DtxdF@disroot.org>
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

link_desc="Create a new jail using an existing one from an installed appjail."

link_main()
{
	local appjail jail

	appjail="$1"
	jail="$2"

	if [ -z "${appjail}" -o -z "${jail}" ]; then
		link_usage
		exit ${EX_USAGE}
	fi

	shift
	
	. "${LIBDIR}/replace"
	. "${LIBDIR}/su"

	link_appjail -c "${CONFIG}" -t "${appjail}" -m "${jail}"
}

link_appjail()
{
	lib_su /bin/sh "${SCRIPTSDIR}/link.sh" $@
}

link_help()
{
	link_usage

	echo
	echo "${link_desc}"
	echo
	echo "This command uses mount_nullfs(8) to mount the jail directory of an"
	echo "installed appjail into a new jail directory. This is useful because"
	echo "you can use the \`appjail jail\` command to edit it and share the"
	echo "new modified jail to a co-worker."
	echo
	echo "  appjail        The name of the appjail to use."
	echo "  jail           The name of the new jail."
}

link_usage()
{
	echo "usage: link appjail jail"
}
