#!/bin/sh
#
# Copyright (c) 2022-2023, Jesús Daniel Colmenares Oviedo <DtxdF@disroot.org>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
# * Neither the name of the copyright holder nor the names of its
#   contributors may be used to endorse or promote products derived from
#   this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

lib_load "${LIBDIR}/check_func"
lib_load "${LIBDIR}/jail"

login_desc="Log into the jail."

login_main()
{
	local _o
	local username="root"
	local jail_name

	while getopts ":u:" _o; do
		case "${_o}" in
			u)
				if lib_check_empty "${OPTARG}"; then
					login_usage
					exit ${EX_USAGE}
				fi
				;;
		esac

		case "${_o}" in
			u)
				username="${OPTARG}"
				;;
			*)
				login_usage
				exit ${EX_USAGE}
				;;
		esac
	done
	shift $((OPTIND-1))

	jail_name="$1"
	if lib_check_empty "${jail_name}"; then
		login_usage
		exit ${EX_USAGE}
	fi

	if ! lib_check_jailname "${jail_name}"; then
		lib_err ${EX_DATAERR} "Invalid jail name \"${jail_name}\""
	fi

	if [ ! -d "${JAILDIR}/${jail_name}/jail" ]; then
		lib_err ${EX_NOINPUT} "Cannot find the jail \`${jail_name}\`"
	fi

	if ! lib_jail_exists "${jail_name}"; then
		lib_warn -- "${jail_name} is not running."
		return 0
	fi

	if ! lib_jail_created_by_appjail "${jail_name}"; then
		lib_warn -- "${jail_name} was not been created by appjail."
		return 0
	fi

	if ! login_check_user "${jail_name}" "${username}"; then
		lib_err ${EX_NOUSER} "The ${username} user does not exist."
	fi

	if ! login_check_shell "${jail_name}" "${username}"; then
		lib_err ${EX_UNAVAILABLE} "The shell for the ${username} user is invalid."
	fi

	jexec -l "${jail_name}" login -f "${username}"
}

login_check_user()
{
	local jail_name="$1"
	local username="$2"

	if [ -z "${jail_name}" -o -z "${username}" ]; then
		lib_err ${EX_USAGE} "login_check_user jail_name username"
	fi

	jexec -l "${jail_name}" id "${username}" > /dev/null 2>&1
}

login_check_shell()
{
	local jail_name="$1"
	local username="$2"
	local shell

	if [ -z "${jail_name}" -o -z "${username}" ]; then
		lib_err ${EX_USAGE} "login_check_shell jail_name username"
	fi

	shell=`jexec -l "${jail_name}" getent passwd "${username}" | cut -d: -f7`

	if lib_check_empty "${shell}"; then
		lib_warn "The shell for ${username} is empty."
		return 1
	fi

	if ! jexec -l "${jail_name}" grep -Ev '^[[:space:]]*#' /etc/shells | grep -Eve '^[[:space:]]*$' | sed -Ee 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' | grep -qwF "${shell}"; then
		lib_warn "The shell for ${username} is not enabled in /etc/shells"
		return 1
	fi

	return 0
}

login_help()
{
	cat << EOF
`login_usage`

${login_desc}

Options:
    -u username        -- The username to try to log in.
EOF
}

login_usage()
{
	cat << EOF
usage: login [-u username] jail
EOF
}
