#!/bin/sh
#
# Copyright (c) 2022, Jesús Daniel Colmenares Oviedo <DtxdF@disroot.org>
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

set_desc="Set the required parameters from the command line."

set_main()
{
	local appjail

	appjail="$1"; shift

	if [ -z "${appjail}" ]; then
		set_usage
		exit ${EX_USAGE}
	fi

	if [ $# -eq 0 ]; then
		set_usage
		exit ${EX_USAGE}
	fi

	. "${LIBDIR}/replace"
	. "${LIBDIR}/su"

	set_key -c "${CONFIG}" -a "${appjail}" $@
}

set_key()
{
	lib_su "${SCRIPTSDIR}/set.sh" $@
}

set_help()
{
	set_usage

	echo
	echo "${set_desc}"
	echo
	echo "set is an alternative to the edit command before starting a jail."
	echo "It is more efficient because you have to know what parameters to"
	echo "set before starting the jail. Also, unlike edit, this command"
	echo "does not require opening a text editor."
	echo
	echo "  appjail        The name of the appjail."
	echo "  keyN=value     The name of the key. Value is the key's value."
	echo "                 May be used multiples times."
}

set_usage()
{
	echo "usage: set appjail key1=value key2=value ... keyN=value"
}
