#!/bin/sh
#
# Copyright (c) 2022-2023, Jesús Daniel Colmenares Oviedo <DtxdF@disroot.org>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
# * Neither the name of the copyright holder nor the names of its
#   contributors may be used to endorse or promote products derived from
#   this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

lib_load "${LIBDIR}/check_func"
lib_load "${LIBDIR}/jail"

STATUS_RUNNING=0
STATUS_NRUNNING=1

status_desc="Show the status of a jail."

status_main()
{
	local _o
	local opt_quiet=0

	while getopts ":q" _o; do
		case "${_o}" in
			q)
				opt_quiet=1
				;;
			*)
				status_usage
				exit ${EX_USAGE}
				;;
		esac
	done
	shift $((OPTIND-1))

	local jail="$1"
	if lib_check_empty "${jail}"; then
		status_usage
		exit ${EX_USAGE}
	fi

	if ! lib_check_jailname "${jail}"; then
		lib_err ${EX_DATAERR} "Invalid jail name \"${jail}\""
	fi

	if [ ! -d "${JAILDIR}/${jail}" ]; then
		lib_err ${EX_NOINPUT} "Cannot find the jail \`${jail}\`"
	fi

	if ! lib_jail_exists "${jail}"; then
		if [ ${opt_quiet} -eq 0 ]; then
			lib_warn -- "${jail} is not running."
		fi

		return ${STATUS_NRUNNING}
	fi

	if ! lib_jail_created_by_appjail "${jail}"; then
		if [ ${opt_quiet} -eq 0 ]; then
			lib_warn -- "${jail} is not running."
		fi

		return ${STATUS_NRUNNING}
	fi

	if [ ${opt_quiet} -eq 0 ]; then
		lib_info -- "${jail} is running."
	fi

	return ${STATUS_RUNNING}
}

status_help()
{
	cat << EOF
`status_usage`

${status_desc}

Options:
    -q        -- Quiet mode.
EOF
}

status_usage()
{
	echo "usage: status [-q] jail"
}
