#!/bin/sh
#
# Copyright (c) 2022, Jesús Daniel Colmenares Oviedo <DtxdF@disroot.org>
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

stop_desc="Remove a jail using a template from an installed appjail."

stop_main()
{
	local _o
	local appjail
	local opts

	while getopts ":T" _o; do
		case "${_o}" in
			T)
				opts="${opts} -${_o}"
				;;
			*)
				stop_usage
				exit ${EX_USAGE}
				;;
		esac
	done
	shift $((OPTIND-1))

	appjail="$1"

	if [ -z "${appjail}" ]; then
		stop_usage
		exit ${EX_USAGE}
	fi

	shift

	. "${LIBDIR}/replace"
	. "${LIBDIR}/su"

	stop_appjail ${opts} -S -c "${CONFIG}" -a "${appjail}" -- $@
}

stop_appjail()
{
	lib_debug "Stopping..."

	lib_su /bin/sh "${SCRIPTSDIR}/service.sh" $@
}

stop_help()
{
	stop_usage

	echo
	echo "${stop_desc}"
	echo
	echo "Before deleting the jail, the *stop functions are executed."
	echo
	echo "  -T             When this is a thinjail, this flag must be used."
	echo "  appjail        Name of the appjail application."
}

stop_usage()
{
	echo "usage: stop [-T] appjail [args]"
}
