#!/bin/sh
#
# Copyright (c) 2022, Jesús Daniel Colmenares Oviedo <DtxdF@disroot.org>
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

uninstall_desc="Remove an installed appjail."

uninstall_main()
{
	. "${LIBDIR}/replace"
	. "${LIBDIR}/su"

	uninstall_jail -c "${CONFIG}" -r "${APPSDIR}" -- $@
}

uninstall_jail()
{
	lib_su /bin/sh "${SCRIPTSDIR}/rm.sh" $@
}

uninstall_help()
{
	uninstall_usage

	echo
	echo "${uninstall_desc}"
	echo
	echo "  appjail             Appjail to remove. May be used multiples times."
}

uninstall_usage()
{
	echo "usage: uninstall appjail..."
}
