APPJAIL_PREFIX="${APPJAIL_PREFIX:-%%PREFIX%%}"

if [ -f "${APPJAIL_PREFIX}/etc/appjail/appjail.conf" ]; then
	. "${APPJAIL_PREFIX}/etc/appjail/appjail.conf"
fi

. "${APPJAIL_PREFIX}/share/appjail/files/default.conf"
