.\"Copyright (c) 2026, Jesús Daniel Colmenares Oviedo <DtxdF@disroot.org>
.\"All rights reserved.
.\"
.\"Redistribution and use in source and binary forms, with or without
.\"modification, are permitted provided that the following conditions are met:
.\"
.\"* Redistributions of source code must retain the above copyright notice, this
.\"  list of conditions and the following disclaimer.
.\"
.\"* Redistributions in binary form must reproduce the above copyright notice,
.\"  this list of conditions and the following disclaimer in the documentation
.\"  and/or other materials provided with the distribution.
.\"
.\"* Neither the name of the copyright holder nor the names of its
.\"  contributors may be used to endorse or promote products derived from
.\"  this software without specific prior written permission.
.\"
.\"THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
.\"AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\"IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
.\"DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
.\"FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\"DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
.\"SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
.\"CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
.\"OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
.\"OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.Dd August 19, 2026
.Dt APPJAIL-SECRETS 1
.Os
.Sh NAME
.Nm appjail-secrets
.Nd Secrets management for jails.
.Sh SYNOPSIS
.Nm appjail secrets
.Cm cat
.Ar group Ns / Ns Ar secret
.Nm appjail secrets
.Op Cm create Ns | Ns Cm update
.Op Fl g Ar gid
.Op Fl m Ar mode
.Op Fl u Ar uid
.Ar group Ns / Ns Ar secret
.Op Ar file
.Nm appjail secrets
.Op Cm create Ns | Ns Cm update
.Op Fl N
.Op Fl g Ar gid
.Op Fl m Ar mode
.Op Fl u Ar uid
.Cm Fl s
.Ar group Ns / Ns Ar secret
.Ar string
.Nm appjail secrets
.Op Cm create Ns | Ns Cm update
.Op Fl g Ar gid
.Op Fl m Ar mode
.Op Fl u Ar uid
.Cm Fl S
.Ar group Ns / Ns Ar secret
.Ar group Ns / Ns Ar secret
.Nm appjail secrets
.Cm init
.Nm appjail secrets
.Cm ls
.Op Fl R
.Oo Ar group Ns Oo Ns / Ns Ar secret Oc Oc
.Nm appjail secrets
.Cm rm
.Ar group Ns / Ns Ar secret
.Nm appjail secrets
.Cm rmdir
.Ar group
.Nm appjail secrets
.Cm use
.Ar group
.Sh DESCRIPTION
.Sy appjail secrets
allows you to manage secrets, that is, any blob of data such as passwords, SSH private
keys, TLS keys, or other data that should not be publicly accessible, except
from authorized jails, in read-only mode and with restricted permissions.
.Pp
In order for jails to use secrets, they must be mounted inside the jail.
This is achieved using the
.Xr appjail-fstab 1
command, but it is strongly recommended to use the
.Sy secret
option in
.Xr appjail-quick 1 Ns ,
not only for simplicity, but also because it automatically creates the entry in
.Xr fstab 5
to mount the secret as read-only and with the correct mountpoint.
.Pp
From the jail perspective, a secret is a read-only directory that may contain files.
That directory is typically
.Pa /secrets/<group>
and may contain zero or more secrets in the format
.Pa /secrets/<group>/<secret> Ns "."
Since secrets are stored on disk in encrypted form, they must be decrypted in
memory so that jails can access them. This is accomplished by using
.Xr mdmfs 8
to create a memory-backed device with an in-memory filesystem of size
.Sy SECRETS_MDMFS_SIZE
.Po see Xr appjail.conf 5 Ns Pc Ns "."
Within that in-memory filesystem, groups of unencrypted secrets are created on
demand and, in the jail’s
.Xr fstab 5 Ns ,
mounted using
.Xr nullfs 4
in read-only mode.
.Pp
Note that the in-memory filesystem is not swap-backed, so secrets remain in
memory until the system is rebooted or the in-memory filesystem is explicitly
unmounted.
.Li -o reserve
.Pq see Xr mdconfig 8
is implicitly set by
.Xr mdmfs 8 Ns ,
so
.Xr mdmfs 8
will either allocate the specified memory or fail, but it is strongly
recommended that you set
.Sy SECRETS_MDMFS_SIZE
to a realistic value.
.Pp
The options are as follows:
.Pp
.Bl -tag -compact -width xxx
.It Cm cat Ar group Ns / Ns Ar secret
Displays the unencrypted content of a secret. The secret is decrypted each time
this command is run.
.Pp
.It Oo Cm create Ns | Ns Cm update Oc Oo Fl g Ar gid Oc Oo Fl m Ar mode Oc Oo Fl u Ar uid Oc Ar group Ns / Ns Ar secret Oo Ar file Oc
.It Oo Cm create Ns | Ns Cm update Oc Oo Fl N Oc Oo Fl g Ar gid Oc Oo Fl m Ar mode Oc Oo Fl u Ar uid Oc Cm Fl s Ar group Ns / Ns Ar secret Ar string
.It Oo Cm create Ns | Ns Cm update Oc Oo Fl g Ar gid Oc Oo Fl m Ar mode Oc Oo Fl u Ar uid Oc Cm Fl S Ar group Ns / Ns Ar secret Ar group Ns / Ns Ar secret 
If you use the
.Cm create
command, a new secret will be created, and, if it does not exist, the corresponding
group will also be created with the specified
.Ar uid Ns ,
.Ar gid Ns ,
and
file
.Ar mode Ns "."
The default values for
.Ar uid
and
.Ar gid
are
.Sy 0 Ns ,
and for file
.Ar mode Ns ,
.Sy 0400 Ns "."
.Pp
In the case of the
.Cm update
command, an existing secret is updated, and if the unencrypted version of
the secret exists in the in-memory filesystem, its contents are also updated.
The uid, gid, and file mode, when not explicitly set, are inherited from the
secret file.
.Pp
By default, if neither the
.Fl s
nor the
.Fl S
flag is set, the second positional argument is a file, and if no file is specified,
the command reads from standard input. If the
.Fl s
flag is set, the secret is created from the string you specified. The
.Fl S
flag
creates a new secret from an existing one.
.Pp
For the
.Fl s
flag, there is the
.Fl N
flag, which prevents a line break from being added at the end of the string.
.Pp
.It Cm init
Create a working directory for
.Sy appjail secrets
with restricted permissions
.Po Sy 0700 Pc Ns ,
so that even if a secret file is created with insecure permissions, other
processes cannot read, write, or execute any files created there.
This command also invokes the backend used to generate the encryption
and decryption keys.
.Pp
This command runs implicitly even if other commands are executed.
.Pp
.It Cm ls Oo Fl R Oc Oo Ar group Ns Oo Ns / Ns Ar secret Oc Oc
Lists existing secrets. If the
.Fl R
flag is set, lists existing secrets on the in-memory filesystem.
.Pp
.It Cm rm Ar group Ns / Ns Ar secret
Delete an existing secret.
.Pp
.It Cm rmdir Ar group
Delete all secrets from the specified group.
.Pp
.It Cm use Ar group
This command creates the memory-backed device and the in-memory filesystem shared
by all secrets, which is done only once, and then creates the group of secrets in
its unencrypted format.
.Pp
This command is implicitly invoked by the
.Sy secret
option in
.Xr appjail-quick 1
or
.Xr appjail-fstab 1 Ns "."
.Pp
.El
.Sh EXIT STATUS
.Ex -std "appjail secrets"
.Sh SEE ALSO
.Xr appjail-fstab 1
.Xr appjail-quick 1
.Xr sysexits 3
.Xr mdconfig 8
.Xr mdmfs 8
.Sh AUTHORS
.An Jesús Daniel Colmenares Oviedo Aq Mt DtxdF@disroot.org
.Sh CAVEATS
Changing the backend by modifying the
.Sy SECRETS_BACKEND
parameter in your
.Xr appjail.conf 5
file does not re-encrypt data that is already encrypted. In fact, it is like
starting from scratch, since each backend uses its own data directory.
The exceptions to this are
.Sy age
and
.Sy rage Ns ,
which use the same data directory.
.Sh SECURITY CONSIDERATIONS
AppJail needs to decrypt data in a non-interactive manner, so it's possible that
some data, such as the keys used by the backends, may be unencrypted. If this
concerns you, you can change
.Sy SECRETS_BACKENDSDIR
to a partition or a ZFS dataset with encryption enabled.
