.\"Copyright (c) 2024, Jesús Daniel Colmenares Oviedo <DtxdF@disroot.org>
.\"All rights reserved.
.\"
.\"Redistribution and use in source and binary forms, with or without
.\"modification, are permitted provided that the following conditions are met:
.\"
.\"* Redistributions of source code must retain the above copyright notice, this
.\"  list of conditions and the following disclaimer.
.\"
.\"* Redistributions in binary form must reproduce the above copyright notice,
.\"  this list of conditions and the following disclaimer in the documentation
.\"  and/or other materials provided with the distribution.
.\"
.\"* Neither the name of the copyright holder nor the names of its
.\"  contributors may be used to endorse or promote products derived from
.\"  this software without specific prior written permission.
.\"
.\"THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
.\"AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\"IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
.\"DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
.\"FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\"DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
.\"SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
.\"CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
.\"OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
.\"OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.Dd March 21, 2024
.Dt APPJAIL.CONF 5
.Os
.Sh NAME
.Nm appjail.conf
.Nd Configuration parameters for AppJail
.Sh SYNOPSIS
.Nm %%PREFIX%%/etc/appjail/appjail.conf
.Sh DESCRIPTION
The
.Xr appjail 1
utility uses some defaults that are safe for most environments, but you can change
any parameters described below to adapt it to your needs.
.Nm
is a file that contains the parameters that control the operation of
.Xr appjail 1 "."
Note that this file is an
.Xr sh 1
script.
.Sh PATH PARAMETERS
.Bl -tag -width xxxxx
.It PREFIX
Root prefix used by other directories.
.br
Default:
.Em %%PREFIX%%
.It LOGDIR
Location of log files.
.br
Default:
.Em /var/log/appjail
.It JAILDIR
Location of jail root directories.
.br
Default:
.Em ${DATADIR}/jails
.It TMPDIR
Location of temporary files. It is highly recommended to use
.Xr tmpfs 5
as the files written here are ephemeral and are not needed after a system reboot.
Additionally, some AppJail operations (e.g. healthcheckers) may be using this
directory during their execution, so if a power outage occurs and after the system
reboots, those files will be there anyway (garbage).
.br
Default:
.Em ${CACHEDIR}/tmp/.appjail
.It GLOBAL_GIT_CACHEDIR
Location of repositories when using the
.Sy git
method in a Makejail file.
.br
Default:
.Em ${CACHEDIR}/git
.El
.Sh SYSTEM DIRECTORIES PARAMETERS
.Bl -tag -width xxxxx
.It SHAREDIR
Location of shared files.
.br
Default:
.Em ${PREFIX}/share/appjail
.It COMMANDS
Location of AppJail commands.
.br
Default:
.Em ${SHAREDIR}/cmd
.It FILESDIR
Location of files used by AppJail.
.br
Default:
.Em ${SHAREDIR}/files
.It LIBDIR
Location of libraries (scripts that contains functions) used by AppJail and their commands.
.br
Default:
.Em ${SHAREDIR}/lib
.It SCRIPTSDIR
Location of scripts used by AppJail.
.br
Default:
.Em ${SHAREDIR}/scripts
.It UTILDIR
Location of utilities used by AppJail.
.br
Default:
.Em ${PREFIX}/libexec/appjail
.It MAKEJAILDIR
Directory used by
.Xr appjail-makejail 1
command.
.br
Default:
.Em ${SHAREDIR}/makejail
.It MAKEJAIL_COMMANDS
Location of Makejail commands.
.br
Default:
.Em ${MAKEJAILDIR}/cmd
.It MAKEJAIL_WCOMMANDS
Location of generators for the creation of the initscript.
.br
Default:
.Em ${MAKEJAILDIR}/write
.It DATADIR
Location of files generated by AppJail.
.br
Default:
.Em ${PREFIX}/appjail
.It CACHEDIR
Location of data that can be reused later.
.br
Default:
.Em ${DATADIR}/cache
.It NETWORKDIR
Location of network's files such as their parameters.
.br
Default:
.Em ${DATADIR}/networks
.It RELEASEDIR
Location of releases created using FreeBSD components or similar (e.g.: debootstrap).
.br
Default:
.Em ${DATADIR}/releases
.It COMPONENTSDIR
Location of FreeBSD components
.Aq base.txz, lib32.txz, ...
.br
Default:
.Em ${CACHEDIR}/components
.El
.Sh ZFS PARAMETERS
.Bl -tag -width xxxxx
.It ENABLE_ZFS
Enable or disable ZFS support. Use
.Sy 0
.Aq default
to disable it and any other value to enable it.
.Pp
.Sy WARNING ":"
Don't enable or disable this parameter after using AppJail, it must be set before use. See
.Dq BUGS/Don't mix ZFS and non-ZFS file systems!
in
.Xr appjail-tutorial 7
for details.
.Pp
Default:
.Em 0
.It ZPOOL
ZFS pool name.
.br
Default:
.Em zroot
.It ZROOTFS
Root prefix but for ZFS datasets. It will be concatenated using the ZFS pool name i.e.
.Em ${ZPOOL}/${ZROOTFS} ","
e.g.:
.Em zroot/appjail "."
.br
Default:
.Em appjail
.It ZOPTS
Optional ZFS parameters for datasets. You must escape characters that can be later interpreted by the shell.
.br
Default:
.Em -o compress=lz4
.El
.Sh DNS PARAMETERS
.Bl -tag -width xxxxx
.It SHORTEN_DOMAIN_NAMES
Use shorter domain names instead of full names, that is, if we enable this parameter
and we have a jail called
.Sy jtest
that is in the
.Sy ajnet
virtual network and with the
suffix
.Sy .appjail ","
instead of resolving
.Sy jtest.ajnet.appjail
we can also resolve
.Sy jtest "."
.br
Default:
.Em 0
.It NETWORK_TO_SHORTEN
The
.Em SHORTEN_DOMAIN_NAMES
parameter only makes sense for a single virtual network; This parameter sets which
virtual network AppJail will use for the aforementioned parameter.
.br
Default:
.Em ${AUTO_NETWORK_NAME}
.It HOST_DOMAIN
Domain suffix for hostnames when the template does not specify the parameter to
explicitly set a hostname
.Aq host.hostname
Also this parameter is used when generating the list of hostnames for each virtual
network, again as a domain suffix.
.br
Default:
.Em .appjail
.El
.Sh TIMEZONE PARAMETERS
.Bl -tag -width xxxxx
.It DEFAULT_TIMEZONE
Parameter equivalent to the
.Sy tzdata
option in
.Xr appjail-quick 1 "."
By default this parameter is set to an empty value.
.br
.It USE_TIMEZONE
Enable or disable the
.Sy tzdata
parameter. See
.Xr appjail-quick 1 "."
.br
Default:
.Em 1
.El
.Sh DEVFS PARAMETERS
.Bl -tag -width xxxxx
.It DEFAULT_DEVFS_RULESET
Default ruleset number to use when the
.Sy devfs_ruleset
parameter is not specified in
.Xr appjail-quick 1 "."
This only makes sense when the
.Sy device
parameter is not specified, since when it is used a number is automatically assigned.
.br
Default:
.Em 5
.It DEFAULT_MOUNT_DEVFS
Parameter equivalent to the
.Sy mount_devfs
option in
.Xr appjail-quick 1 "."
.br
Default:
.Em 0
.It DEVFS_ASSIGN_ALGO
What algorithm to use to assign a ruleset number when using the
.Sy device
parameter in
.Xr appjail-quick 1 ":"
.Pp
.Bl -dash
.It
fsmn
.Aq Find Smallest Missing Number
.Pp
This algorithm will select an smallest unused number from a list of numbers.
It takes into account the length of the list. If the list has a length of
.Sy 0 ","
the unused number is
.Sy 1 ";"
if the length is
.Sy 1 ","
so the list has one element, the algorithm checks if that element is
.Sy 1 ","
if so, the unused number is
.Sy 2 ","
if not,
is
.Sy 1 "."
If this check is unsuccessful, the algorithm does an N/2 linear search
to compare two numbers starting from
.Sy 1
up to the length of the list. If nothing matches, the last element plus
.Sy 1
is the unused number.
.Pp
.It
fnfs
.Aq Find Number From Start
.Pp
This algorithm selects a given number from a list of numbers. If this number is
already in use, the number is incremented and the search continues. Once this
search is finished, the resulting number is the unused. As
.Em fsmn ","
it takes the length of the list. If the list has a length of
.Sy 0 ","
the resulting number is the same as the given number.
.Pp
.El
You don't need to worry about the details, but for the record: both algorithms assume that the list is sorted and that all elements are unique. The list of numbers is the output of the
.Em devfs rule showsets
command plus the assigned ruleset numbers of other jails.
.Pp
Use
.Sy fsmn
if you have no problem assigning lower numbers, if you don't edit
.Xr devfs.rules 5
frequently, or if you have rulesets with a higher number in that file.
.Pp
Use
.Sy fnfs
is you want a more deterministic way of assigning a ruleset number.
.Pp
.br
Default:
.Em fsmn
.It DEVFS_FNFS
Initial number used by
.Sy fnfs "."
.br
Default:
.Em 1000
.El
.Sh JAIL PARAMETERS
.Bl -tag -width xxxxx
.It VOLUMESDIR
Location of the root directory inside the jail for volumes that don't have a mountpoint explicitly set.
.br
Default:
.Em /volumes
.It DEFAULT_TEMPLATE
Default template that will be used by some operations such as
.Xr appjail-start 1
or
.Xr appjail-quick 1 "."
.br
Default:
.Em ${FILESDIR}/default_template.conf
.It DEFAULT_BOOT
Parameter equivalent to the
.Sy boot
option in
.Xr appjail-quick 1 "."
.br
Default:
.Em 1
.It DEFAULT_PACKAGES
Parameter equivalent to the
.Sy pkg
option in
.Xr appjail-quick 1 "."
By default this parameter is set to an empty value.
.It DEFAULT_PRIORITY
Parameter equivalent to the
.Sy priority
option in
.Xr appjail-quick 1 "."
.br
Default:
.Em 0
.It DEFAULT_START
Parameter equivalent to the
.Sy start
option in
.Xr appjail-quick 1 "."
.br
Default:
.Em 0
.It DEFAULT_RESTART
Parameter equivalent to the
.Sy restart
option in
.Xr appjail-quick 1 "."
This parameter requires option
.Sy start
to be used.
.br
Default:
.Em 0
.It DEFAULT_RUN
Parameter equivalent to the
.Sy run
option in
.Xr appjail-quick 1 "."
This parameter requires option
.Sy start
to be used.
.br
Default:
.Em 0
.It DEFAULT_LOGIN
Parameter equivalent to the
.Sy login
option in
.Xr appjail-quick 1 "."
This parameter requires option
.Sy start
to be used.
.br
Default:
.Em 0
.It DEFAULT_LOGIN_USER
Parameter equivalent to the
.Sy login_user
option in
.Xr appjail-quick 1 "."
.br
Default:
.Em root
.It DEFAULT_COPYDIR
Parameter equivalent to the
.Sy copydir
option in
.Xr appjail-quick 1 "."
.br
Default:
.Em /
.It DEFAULT_OVERWRITE
Parameter equivalent to the
.Sy overwrite
option in
.Xr appjail-quick 1 "."
.br
Default:
.Em 0
.El
.Sh STARTUP PARAMETERS
.Bl -tag -width xxxxx
.It USE_PARALLEL
Start and stop jails in parallel.
.It USE_PARALLEL_NATNET
Perform NAT per network in parallel.
.El
.Sh NETWORK PARAMETERS
.Bl -tag -width xxxxx
.It AUTO_NETWORK_ADDR
Network address. This and the below parameters are used by the
.Sy auto-create
subcommand in
.Xr appjail-network 1
to create a virtual network when none are specified in
.Xr appjail-quick 1 "."
.br
Default:
.Em 10.0.0.0/10
.It AUTO_NETWORK_NAME
Network name.
.br
Default:
.Em ajnet
.It AUTO_NETWORK_DESC
Network description.
.br
Default:
.Em AppJail network
.It USE_FIREWALL
Packet filter or firewall to use.
.Sy pf ","
.Sy ipfw
and
.Sy ipfilter
are valid values, but currently only
.Sy pf
is supported.
.br
Default:
.Em pf
.It EXT_IF
External interface.
By default, AppJail will automatically get the external interface, but it is highly
recommended to set this parameter explicitly to improve performance and stability.
Performance improves because AppJail relies on you for this task, so it does not
need to get the external interface for each execution. Stability is improved
because the external interface may not be valid if e.g. it is unplugged or you have
multiple interfaces and you want to choose one of them as the external interface.
.It ON_IF
Network interface or group name to transmit packets on.
.br
Default:
.Em ${EXT_IF}
.It SHARED_BRIDGE
Shared bridge to be created by the
.Sy attach
subcommand in
.Xr appjail-network 1
and also used by the
.Sy detach
subcommand.
.br
Default:
.Em appjail
.It DEFAULT_MTU
If an epair interface is provided before a non-epair interface, use this MTU.
The non-epair interface should be provided before the epair interface, so
that AppJail can obtain the MTU and set the bridge MTU correctly. Remember
that
.Xr if_bridge 4
requires that all interfaces have the same MTU; see
.Xr if_bridge 4
for more details.
.Pp
If you are not sure which MTU to choose, use
.Sy 576 "."
See
.Em RFC 791
for more details.
.Pp
This parameter is used by the
.Sy attach
subcommand in
.Xr appjail-network 1 "."
.Pp
Default:
.Em 1500
.It DEFAULT_VIRTUALNET_MTU
Default MTU used by Virtual Networks.
.Pp
Note that if you have a Virtual Network already created with no MTU defined, this
value will be used every time when an 
.Xr if_epair 4
interface is created, so don't change this value when you have already added a member
to the bridge with a different MTU, this will result in an error.
See 
.Xr if_bridge 4
for details.
.Pp
Default:
.Em 1500
.It DEFAULT_RESOLV_CONF
Parameter equivalent to the
.Sy resolv_conf
option in
.Xr appjail-quick 1 "."
.br
Default:
.Em /etc/resolv.conf
.It USE_RESOLV_CONF
Enable or disable the
.Sy resolv_conf
parameter. See
.Xr appjail-quick 1 "."
.br
Default:
.Em 1
.El
.Sh LOG PARAMETERS
.Bl -tag -width xxxxx
.It CREATED_FORMAT
.Xr date 1
format to display in a human-understandable format for the
.Sy created
keyword in the
.Sy list
or 
.Sy get
subcommands of
.Xr appjail-jail 1 "."
.br
Default:
.Em %Y-%m-%d %H:%M:%S
.It CONSOLELOG_NAME
Command to run to generate a filename for the
.Sy exec.consolelog
parameter in a template. The slash character can't be used.
.br
Default:
.Em date +%Y-%m-%d.log
.It SESSION_ID_NAME
Command to run to generate a filename for when the
.Sy ENABLE_LOGGING_OUTPUT
parameter is set to a value other than
.Sy 0 "."
The slash character can't be used.
.br
Default:
.Em date +%Y-%m-%d.log
.It STARTUPLOG_NAME
Command to run to generate a filename for logs generated by the
.Xr appjail-startup 1
command. The slash character can't be used.
.br
Default:
.Em date +%Y-%m-%d.log
.It BUILDLOG_NAME
Command to run to generate a filename for logs generated by the
.Xr appjail-fetch 1
command when building the FreeBSD source. The slash character can't be used.
.br
Default:
.Em date +%Y-%m-%d_%Hh%Mm%Ss.log 
.It ETCUPDATELOG_NAME
Command to run to generate a filename for logs generated by the
.Xr appjail-etcupdate 1
command. The slash character can't be used.
.br
Default:
.Em date +%Y-%m-%d_%Hh%Mm%Ss.log
.It ENABLE_LOGGING_OUTPUT
Records the AppJail session, that is, from the first time it is run until it ends.
.br
Default:
.Em 0
.It SCRIPT_TIME
See
.Fl t
in
.Xr script 1 "."
.br
Default:
.Em 30
.It ENABLE_DEBUG
There are four levels of debugging:
.Sy debug ","
.Sy info ","
.Sy warn
and
.Sy error "."
Only the
.Sy debug
level can be enabled or disabled.
.br
Default:
.Em 1
.El
.Sh FETCH PARAMETERS
.Bl -tag -width xxxxx
.It DEFAULT_FETCH_METHOD
Default
.Xr appjail-fetch 1
subcommand to be executed when none is provided.
.br
Default:
.Em www
.It DEFAULT_INSTALL_METHOD
Default
.Xr appjail-jail 1
installation method for creating new jails.
.br
Default:
.Em standard
.It DOWNLOADURL
Site where FreeBSD components will be downloaded. The protocols that can be used
depend entirely on the command specified in the
.Sy WWW_CMD
parameter.
.Pp
The value of this parameter may contain some keywords that have special meaning:
.Bl -dash -compact
.It
.Sy %a
.Aq Architecture
.It
.Sy %v
.Aq Version
.El
.Pp
AppJail will quote the keyword's value at runtime and escape any characters that can
be interpreted by the shell. If you want to escape a keyword, use %%, e.g. %%v.
.Pp
Default:
.Em https://download.freebsd.org/releases/%a/%v
.It COMPONENTS
Default components to be downloaded when none are specified.
.br
Default:
.Em base.txz
.It DEFAULT_RELEASE
Default release name when none is specified.
.br
Default:
.Em default
.It WWW_CMD
Command to download FreeBSD components.
.Pp
The value of this parameter may contain some keywords that have special meaning:
.Bl -dash -compact
.It
.Sy %o
.Aq Component pathname
.It
.Sy %u
.Aq Site where FreeBSD components will be downloaded
.It 
.Sy %c
.Aq Component filename
.El
.Pp
AppJail will quote the keyword's value at runtime and escape any characters that can
be interpreted by the shell. If you want to escape a keyword, use %%, e.g. %%c.
.Pp
Default:
.Em fetch -Rpm -o %o %u/%c
.It MAKEJAIL_FETCH_CMD
Command to get a Makejail when using the
.Sy fetch
method in
.Xr appjail-makejail 1 "."
.Pp
The value of this parameter may contain some keywords that have special meaning:
.Bl -dash -compact
.It
.Sy %o
.Aq Makejail pathname
.It
.Sy %u
.Aq Site where the Makejail file will be downloaded
.El
.Pp
AppJail will quote the keyword's value at runtime and escape any characters that can
be interpreted by the shell. If you want to escape a keyword, use %%, e.g. %%u.
.Pp
Default:
.Em fetch -Rpm -o %o %u
.It MAKEJAIL_ADD_FETCH_CMD
Command to get the tarball file used by the
.Sy ADD
instruction in a Makejail file.
.Pp
The value of this parameter may contain some keywords that have special meaning:
.Bl -dash -compact
.It
.Sy %u
.Aq Site where the tarball will be downloaded
.El
.Pp
AppJail will quote the keyword's value at runtime and escape any characters that can
be interpreted by the shell. If you want to escape a keyword, use %%, e.g. %%u.
.Pp
Default:
.Em fetch -Rpm -o - %u
.El
.Sh SOURCE BUILD PARAMETERS
.Bl -tag -width xxxxx
.It SRCDIR
Location of FreeBSD source tree.
.br
Default:
.Em /usr/src
.It TARGET_ARCH
Default value for the
.Sy TARGET
and
.Sy TARGET_ARCH
variables. See
.Xr appjail-fetch 1
and
.Xr build 7
for details.
.br
Default:
.Em ${FREEBSD_ARCH}
.It MAKEARGS
Default arguments used by
.Xr make 1
when building the source tree. By default this parameter is set to an empty value.
.It KERNEL
Default kernel to compile.
.br
Default:
.Em GENERIC
.It JOBS
Number of jobs. By default, the number of CPUs of the system.
.El
.Sh IMAGE PARAMETERS
.Bl -tag -width xxxxx
.It IMAGESDIR
Location of images.
.br
Default:
.Em ${CACHEDIR}/images
.It IMAGE_COMPRESS
Default algorithm to compress the images.
.br
Default:
.Em xz
.It IMAGE_ARCH
Default target to build the images. If not defined, the output of the
.Fl p
parameter of the
.Xr uname 1
command is used. By default this parameter is set to an empty value.
.It IMAGE_TAG
Default image tag.
.br
Default:
.Em latest
.It IMAGE_FETCH_CMD
Command to get a
.Sy ajspec
file when using the
.Sy fetch
method in the
.Sy import
subcommand of the
.Xr appjail-image 1
command.
.Pp
The value of this parameter may contain some keywords that have special meaning:
.Bl -dash -compact
.It
.Sy %o
.Aq Image pathname
.It
.Sy %u
.Aq Site where the image will be downloaded
.El
.Pp
AppJail will quote the keyword's value at runtime and escape any characters that can
be interpreted by the shell. If you want to escape a keyword, use %%, e.g. %%u.
.Pp
.br
Default:
.Em fetch -Rpm -o %o %u
.It IMAGE_ENTRYPOINT
If no entrypoint is specified in a Makejail file, use this parameter as the default
value. This value will be concatenated like a pathname, e.g.
.Sy <entrypoint>/<image name> "."
.br
Default:
.Em gh+AppJail-makejails
.It IMAGE_DOWNLOAD_METHOD
The
.Xr appjail-image 1
command will get a list of sources to try to download the image to one of them, if this parameter is set to
.Sy seq
the attempts are made as it is in the list defined in the
.Sy ajspec
file, but if this parameter is set to
.Sy random ","
the list is sorted randomly before trying to download the image.
.br
Default:
.Em random
.El
.Sh DEBOOTSTRAP PARAMETERS
.Bl -tag -width xxxxx
.It DEBOOTSTRAP_CMD
.Xr debootstrap 8
command to bootstrap a basic debian system.
.Pp
The value of this parameter may contain some keywords that have special meaning:
.Bl -dash -compact
.It
.Sy %a
.Aq Target architecture
.It
.Sy %s
.Aq Suite name
.It
.Sy %o
.Aq Output directory
.El
.Pp
AppJail will quote the keyword's value at runtime and escape any characters that can
be interpreted by the shell. If you want to escape a keyword, use %%, e.g. %%s.
.Pp
Default:
.Em debootstrap --foreign --arch=%a --no-check-gpg %s %o
.It DEBOOTSTRAP_ARCH
Default target architecture used by the
.Xr debootstrap 8
command.
.br
Default:
.Em ${FREEBSD_ARCH}
.It DEBOOTSTRAP_MIRROR
See
.Xr debootstrap 8 "."
By default this parameter is set to an empty value.
.It DEBOOTSTRAP_SCRIPT
See
.Xr debootstrap 8 "."
By default this parameter is set to an empty value.
.It APT_CACHE_START
See
.Em Cache-Start
in
.Xr apt.conf 5 "."
.br
Default:
.Em 251658240
.El
.Sh COLORS PARAMETERS
.Bl -tag -width xxxxx
.It ENABLE_COLORS
Enable or disable colors. It is highly recommended to use colors to more easily identify errors, warnings, and so on. Use the
.Fl R
parameter in
.Xr less 1
if you want to see a log created by AppJail when this parameter is enabled.
.br
Default:
.Em 1
.It ENABLE_RANDOM_COLORS
Some commands set a prefix before displaying a message which is commonly the target
name, i.e. jail name, image name, etc. That prefix can be displayed colored with a
randomly chosen color by enabling this parameter.
.br
Default:
.Em 1
.El
.Sh HEALTHCHECKERS PARAMETERS
.Bl -tag -width xxxxx
.It DEFAULT_HEALTH_TYPE
Default health type when the user doesn't specify one.
.br
Default:
.Em host
.It DEFAULT_RECOVER_TYPE
Default recover type when the user doesn't specify one.
.br
Default:
.Em host
.It DEFAULT_HEALTH_CMD
Default health command when the user doesn't specify one.
.Pp
The value of this parameter may contain some keywords that have special meaning:
.Bl -dash -compact
.It
.Sy %j
.Aq Jail name
.El
.Pp
AppJail will quote the keyword's value at runtime and escape any characters that can
be interpreted by the shell. If you want to escape a keyword, use %%, e.g. %%j.
.Pp
Default:
.Em appjail status -q %j
.It DEFAULT_RECOVER_CMD
Default recover command when the user doesn't specify one
.Pp
The value of this parameter may contain some keywords that have special meaning:
.Bl -dash -compact
.It
.Sy %j
.Aq Jail name
.El
.Pp
AppJail will quote the keyword's value at runtime and escape any characters that can
be interpreted by the shell. If you want to escape a keyword, use %%, e.g. %%j.
.Pp
Default:
.Em appjail restart %j
.It DEFAULT_HEALTH_INTERVAL
Default interval number to execute the health command
.br
Default:
.Em 30
.It DEFAULT_HEALTH_RETRIES
Default number of attempts before executing the recover command.
.br
Default:
.Em 3
.It DEFAULT_HEALTH_START_PERIOD
Delay before running the healthchecker. If this parameter is set to
.Sy 0 ","
no delay is performed.
.br
Default:
.Em 0
.It DEFAULT_RECOVER_TOTAL
Default number of attempts before considering the jail as unhealthy.
.br
Default:
.Em 3
.It DEFAULT_HEALTH_TIMEOUT
Duration of the health command before sending the signal specified in the
.Sy DEFAULT_TIMEOUT_SIGNAL "."
.br
Default:
.Em 120
.It DEFAULT_TIMEOUT_SIGNAL
Signal to send once the timeout specified in
.Sy DEFAULT_HEALTH_TIMEOUT
has been reached.
.br
Default:
.Em sigterm
.It DEFAULT_TIMEOUT_KILL_AFTER
Send a
.Sy SIGKILL
signal after sending the signal specified in the
.Sy DEFAULT_TIMEOUT_SIGNAL
parameter.
.br
Default:
.Em 180
.It DEFAULT_RECOVER_TIMEOUT
Duration of the recover command before sending the signal specified in the
.Sy DEFAULT_RECOVER_TIMEOUT_SIGNAL "."
.br
Default:
.Em 120
.It DEFAULT_RECOVER_TIMEOUT_SIGNAL
Signal to send once the timeout specified in
.Sy DEFAULT_RECOVER_TIMEOUT
has been reached.
.br
Default:
.Em sigterm
.It DEFAULT_RECOVER_TIMEOUT_KILL_AFTER
Send a
.Sy SIGKILL
signal after sending the signal specified in the
.Sy DEFAULT_RECOVER_TIMEOUT_SIGNAL
parameter.
.br
Default:
.Em 180
.El
.Sh COMPRESSION/DECOMPRESSION PARAMETERS
The following parameters are self-explanatory.
.Pp
Parameters prefixed with
.Sy TAR
apply to operations related with
.Xr tar 1
such as
.Sy TAR_ARGS ","
.Sy TAR_COMPRESS_ARGS ","
.Sy TAR_DECOMPRESS_ARGS
and
.Sy TAR_<ALGO>_ARGS.
.Pp
Parameters such as
.Sy <ALGO>_ARGS ","
.Sy <ALGO>_COMPRESS_ARGS ","
.Sy <ALGO>_COMPRESS_CMD ","
.Sy <ALGO>_DECOMPRESS_ARGS
and
.Sy <ALGO>_DECOMPRESS_CMD
apply to compression and decompression-related operations that use
.Sy <ALGO>_COMPRESS_CMD
for compress and
.Sy <ALGO>_DECOMPRESS_CMD
for decompress, i.e. export and import ZFS images.
.Pp
.Bl -tag -width xxxxx
.It TAR_ARGS
By default this parameter is set to an empty value.
.It TAR_COMPRESS_ARGS
Default:
.Em ${TAR_ARGS}
.It TAR_DECOMPRESS_ARGS
Default:
.Em ${TAR_ARGS}
.It TAR_BZIP_ARGS
Default:
.Em ${TAR_COMPRESS_ARGS} --bzip
.It TAR_GZIP_ARGS
Default:
.Em ${TAR_COMPRESS_ARGS} --gzip
.It TAR_LRZIP_ARGS
You need to install
.Em archivers/lrzip
to use this algorithm.
.Pp
Default:
.Em ${TAR_COMPRESS_ARGS} --lrzip
.It TAR_LZ4_ARGS
Default:
.Em ${TAR_COMPRESS_ARGS} --lz4
.It TAR_LZMA_ARGS
Default:
.Em ${TAR_COMPRESS_ARGS} --lzma
.It TAR_LZOP_ARGS
You need to install
.Em archivers/lzop
to use this algorithm.
.Pp
Default:
.Em ${TAR_COMPRESS_ARGS} --lzop
.It TAR_XZ_ARGS
Default:
.Em ${TAR_COMPRESS_ARGS} --xz
.It TAR_ZSTD_ARGS
Default:
.Em ${TAR_COMPRESS_ARGS} --zstd
.It BZIP_ARGS
By default this parameter is set to an empty value.
.It BZIP_COMPRESS_ARGS
Default:
.Em ${BZIP_ARGS}
.It BZIP_COMPRESS_CMD
Default:
.Em bzip2 ${BZIP_COMPRESS_ARGS}
.It BZIP_DECOMPRESS_ARGS
Default:
.Em ${BZIP_ARGS}
.It BZIP_DECOMPRESS_CMD
Default:
.Em bzip2 ${BZIP_DECOMPRESS_ARGS} -d
.It GZIP_ARGS
By default this parameter is set to an empty value.
.It GZIP_COMPRESS_ARGS
Default:
.Em ${GZIP_ARGS}
.It GZIP_COMPRESS_CMD
Default:
.Em gzip ${GZIP_COMPRESS_ARGS}
.It GZIP_DECOMPRESS_ARGS
Default:
.Em ${GZIP_ARGS}
.It GZIP_DECOMPRESS_CMD
Default:
.Em gzip -d ${GZIP_DECOMPRESS_ARGS}
.It LRZIP_ARGS
By default this parameter is set to an empty value.
.Pp
You need to install
.Em archivers/lrzip
to use this algorithm.
.It LRZIP_COMPRESS_ARGS
Default:
.Em ${LRZIP_ARGS}
.It LRZIP_COMPRESS_CMD
Default:
.Em lrzip ${LRZIP_COMPRESS_ARGS}
.It LRZIP_DECOMPRESS_ARGS
Default:
.Em ${LRZIP_ARGS}
.It LRZIP_DECOMPRESS_CMD
Default:
.Em lrzip -d ${LRZIP_DECOMPRESS_ARGS}
.It LZ4_ARGS
By default this parameter is set to an empty value.
.It LZ4_COMPRESS_ARGS
Default:
.Em ${LZ4_ARGS}
.It LZ4_COMPRESS_CMD
Default:
.Em lz4 ${LZ4_COMPRESS_ARGS}
.It LZ4_DECOMPRESS_ARGS
Default:
.Em ${LZ4_ARGS}
.It LZ4_DECOMPRESS_CMD
Default:
.Em lz4 -d ${LZ4_DECOMPRESS_ARGS}
.It LZMA_ARGS
By default this parameter is set to an empty value.
.It LZMA_COMPRESS_ARGS
Default:
.Em ${LZMA_ARGS}
.It LZMA_COMPRESS_CMD
Default:
.Em lzma ${LZMA_COMPRESS_ARGS}
.It LZMA_DECOMPRESS_ARGS
Default:
.Em ${LZMA_ARGS}
.It LZMA_DECOMPRESS_CMD
Default:
.Em lzma -d ${LZMA_DECOMPRESS_ARGS}
.It LZOP_ARGS
By default this parameter is set to an empty value.
.Pp
You need to install
.Em archivers/lzop
to use this algorithm.
.br
.It LZOP_COMPRESS_ARGS
Default:
.Em ${LZOP_ARGS}
.It LZOP_COMPRESS_CMD
Default:
.Em lzop ${LZOP_COMPRESS_ARGS}
.It LZOP_DECOMPRESS_ARGS
Default:
.Em ${LZOP_ARGS}
.It LZOP_DECOMPRESS_CMD
Default:
.Em lzop -d ${LZOP_DECOMPRESS_ARGS}
.It XZ_ARGS
By default this parameter is set to an empty value.
.It XZ_COMPRESS_ARGS
Default:
.Em ${XZ_ARGS}
.It XZ_COMPRESS_CMD
Default:
.Em xz ${XZ_COMPRESS_ARGS}
.It XZ_DECOMPRESS_ARGS
Default:
.Em ${XZ_ARGS}
.It XZ_DECOMPRESS_CMD
Default:
.Em xz -d ${XZ_DECOMPRESS_ARGS}
.It ZSTD_ARGS
By default this parameter is set to an empty value.
.It ZSTD_COMPRESS_ARGS
Default:
.Em ${ZSTD_ARGS}
.It ZSTD_COMPRESS_CMD
Default:
.Em zstd ${ZSTD_COMPRESS_ARGS}
.It ZSTD_DECOMPRESS_ARGS
Default:
.Em ${ZSTD_ARGS}
.It ZSTD_DECOMPRESS_CMD
Default:
.Em zstd -d ${ZSTD_DECOMPRESS_ARGS}
.El
.Sh MISCELLANEOUS PARAMETERS
.Bl -tag -width xxxxx
.It AUTO_GIT_UPDATE
If there is a request to clone a repository in a Makejail file and it already exists
locally, update it.
.br
Default:
.Em 1
.It FREEBSD_UPDATE_CONF
Default
.Xr freebsd-update.conf 5
configuration file when updating or upgrading a FreeBSD jail or release.
.br
Default:
.Em /etc/freebsd-update.conf
.It FREEBSD_ARCH
Default architecture used by some operations, such as fetching FreeBSD components,
creating jails, etc. If not defined, the output of the
.Fl m
parameter of the
.Xr uname 1
command is used. By default this parameter is set to an empty value.
.It FREEBSD_VERSION
Default FreeBSD version without the patch level used by some operations, such as
fetching FreeBSD components, creating jails, etc. If not defined, AppJail will
get a valid version string.
.It RUNAS
Utility that runs when a non-root user runs
.Xr appjail 1 "."
See
.Xr appjail-user 8 "."
.br
Default:
.Em doas
.El
.Sh FILES
.Pa %%PREFIX%%/etc/appjail/appjail.conf
.Pa %%PREFIX%%/etc/appjail/appjail.conf.sample
.Sh SEE ALSO
.Xr appjail 1
.Xr appjail-devfs 1
.Xr appjail-fetch 1
.Xr appjail-image 1
.Xr appjail-makejail 1
.Xr appjail-nat 1
.Xr appjail-network 1
.Xr appjail-quick 1
.Xr appjail-volume 1
.Xr appjail-zfs 1
.Xr tar 1
.Xr if_bridge 4
.Xr if_epair 4
.Xr freebsd-update.conf 5
.Xr appjail-tutorial 7
.Xr appjail-dns 8
.Sh AUTHORS
.An Jesús Daniel Colmenares Oviedo Aq Mt DtxdF@disroot.org
