#!/bin/sh
#
# Copyright (c) 2022-2023, Jesús Daniel Colmenares Oviedo <DtxdF@disroot.org>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
# * Neither the name of the copyright holder nor the names of its
#   contributors may be used to endorse or promote products derived from
#   this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

. "${AJ_CONFIG}"
. "${LIBDIR}/load"

lib_load "${SCRIPTSDIR}/default_env.sh"
lib_load "${LIBDIR}/log"
lib_load "${LIBDIR}/check_func"
lib_load "${LIBDIR}/jail"
lib_load "${LIBDIR}/replace"

main()
{
	local args="$1"
	if lib_check_empty "${args}"; then
		lib_err - "usage: CMD --chroot [cmd [args ...]]"
		lib_err - "       CMD --jaildir [cmd [args ...]]"
		lib_err - "       CMD [--jexec] [--noclean] [--juser jail_username | --huser host_username] [cmd [args ...]]"
		lib_err - "       CMD --local [cmd [args ...]]"
		lib_err - "       CMD --local-jaildir [cmd [args ...]]"
		lib_err - "       CMD --local-rootdir [cmd [args ...]]"
		exit ${EX_USAGE}
	fi

	# Options
	local use_chroot=0
	local use_jaildir=0
	local use_jexec=1
	local use_local=0
	local use_local_jaildir=0
	local use_local_rootdir=0

	# jexec options
	local noclean=0
	local juser=
	local huser=

	# Arguments
	local args_list=`lib_split_jailparams "${args}"`
	local total_items=`printf "%s\n" "${args_list}" | wc -l`
	local current_index=0
	
	while [ ${current_index} -lt ${total_items} ]; do 
		current_index=$((current_index+1))
		local arg=`printf "%s\n" "${args_list}" | head -${current_index} | tail -n 1`
		if lib_check_empty "${arg}"; then
			continue
		fi

		local optarg=
		case "${arg}" in
			--juser|--huser)
				current_index=$((current_index+1))
				if [ ${current_index} -eq ${total_items} ]; then
					main # usage
				fi

				optarg=`printf "%s\n" "${args_list}" | head -${current_index} | tail -n 1`
				if lib_check_empty "${optarg}"; then
					main # usage
				fi
				;;
		esac

		case "${arg}" in
			--chroot)
				use_chroot=1
				;;
			--jaildir)
				use_jaildir=1
				;;
			--jexec)
				use_jexec=1
				;;
			--local)
				use_local=1
				;;
			--local-jaildir)
				use_local_jaildir=1
				;;
			--local-rootdir)
				use_local_rootdir=1
				;;
			--noclean)
				noclean=1
				;;
			--huser)
				huser="${optarg}"
				;;
			--juser)
				juser="${optarg}"
				;;
			--)
				break
				;;
			--*)
				main # usage
				;;
			*)
				break
				;;
		esac
	done
	current_index=$((current_index-1))

	local escape_chars='`"\'

	local command=

	if [ ${use_chroot} -eq 1 ]; then
		command="\"\${APPJAIL_SCRIPT}\" cmd chroot \"\${APPJAIL_JAILNAME}\""
	elif [ ${use_jaildir} -eq 1 ]; then
		command="\"\${APPJAIL_SCRIPT}\" cmd jaildir \"\${APPJAIL_JAILNAME}\""
	elif [ ${use_local} -eq 1 ]; then
		command=
	elif [ ${use_local_jaildir} -eq 1 ]; then
		command="\"\${APPJAIL_SCRIPT}\" cmd local \"\${APPJAIL_JAILNAME}\" -j"
	elif [ ${use_local_rootdir} -eq 1 ]; then
		command="\"\${APPJAIL_SCRIPT}\" cmd local \"\${APPJAIL_JAILNAME}\" -r"
	elif [ ${use_jexec} -eq 1 ]; then
		local jexec_args=

		if [ ${noclean} -eq 1 ]; then
			jexec_args="-l"
		fi

		if [ -n "${huser}" ]; then
			local escape_huser=`lib_escape_string "${huser}" "" "${escape_chars}"`

			jexec_args="${jexec_args} -U \"${escape_huser}\""
		elif [ -n "${juser}" ]; then
			local escape_juser=`lib_escape_string "${juser}" "" "${escape_chars}"`

			jexec_args="${jexec_args} -u \"${escape_juser}\""
		fi

		command="\"\${APPJAIL_SCRIPT}\" cmd jexec \"\${APPJAIL_JAILNAME}\" ${jexec_args}"
	fi

	args_list=`lib_split_ujailparams "${args}"`

	local cmd_args=
	while [ ${current_index} -lt ${total_items} ]; do 
		current_index=$((current_index+1))

		local cmd=`printf "%s\n" "${args_list}" | head -${current_index} | tail -n 1`

		if [ -z "${cmd_args}" ]; then
			cmd_args="${cmd}"
		else
			cmd_args="${cmd_args} ${cmd}"
		fi
	done

	cmd_args=`lib_replace_escape_shellvars "${cmd_args}"`

	command="${command} sh -c \"${cmd_args}\""

	printf "%s\n" "${command}"
}

main "$@"
