#!/bin/sh
#
# Copyright (c) 2022-2025, Jesús Daniel Colmenares Oviedo <DtxdF@disroot.org>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
# * Neither the name of the copyright holder nor the names of its
#   contributors may be used to endorse or promote products derived from
#   this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

. "${AJ_CONFIG}"
. "${LIBDIR}/load"

lib_load "${LIBDIR}/log"
lib_load "${LIBDIR}/check_func"
lib_load "${LIBDIR}/jail"
lib_load "${LIBDIR}/replace"

main()
{
	local args="$1"
	if lib_check_empty "${args}"; then
		lib_err ${EX_USAGE} "usage: DESTROY [--force] [--with-all-dependents] <jail>"
	fi
	
	# Options
	local opt_force=0
	local opt_with_all_dependents=0
	
	# Arguments
	local args_list
	local total_items
	local current_index=0

	args_list=`lib_split_jailparams "${args}"` || exit $?
	total_items=`printf "%s\n" "${args_list}" | wc -l`
	
	while [ ${current_index} -lt ${total_items} ]; do 
		current_index=$((current_index+1))
		local arg=`printf "%s\n" "${args_list}" | head -${current_index} | tail -n 1`
		if lib_check_empty "${arg}"; then
			continue
		fi

		case "${arg}" in
			--force)
				opt_force=1
				;;
			--with-all-dependents)
				opt_with_all_dependents=1
				;;
			--)
				break
				;;
			--*)
				main # usage
				;;
			*)
				break
				;;
		esac
	done

	local jail_name=`printf "%s\n" "${args_list}" | head -${current_index} | tail -n 1`

	local escape_chars
	escape_chars='`"\'

	local escape_jail_name=`lib_escape_string "${jail_name}" "" "${escape_chars}"`

	local destroy_args=
	if [ ${opt_force} -eq 1 ]; then
		destroy_args="-f"
	fi

	if [ ${opt_with_all_dependents} -eq 1 ]; then
		destroy_args="${destroy_args} -R"
	fi

	echo "__APPJAIL_DESTROY_EPHEMERAL__=\`"\${APPJAIL_SCRIPT}" jail get -I -- \"${escape_jail_name}\" ephemeral\` || exit \$?"

	echo "if appjail status -q -- \"${escape_jail_name}\"; then"
	echo "    __APPJAIL_DESTROY_UP__=true"
	echo "else"
	echo "    __APPJAIL_DESTROY_UP__=false"
	echo "fi"

	echo "if \${__APPJAIL_DESTROY_UP__}; then"
	echo "    appjail stop -- \"${escape_jail_name}\" || exit \$?"
	echo "fi"

	echo "if [ \${__APPJAIL_DESTROY_EPHEMERAL__} -eq 0 ] || ! \${__APPJAIL_DESTROY_UP__}; then"
	echo "    appjail jail destroy ${destroy_args} -- \"${escape_jail_name}\" || exit \$?"
	echo "fi"
}

main "$@"
