#!/bin/sh
#
# Copyright (c) 2022-2023, Jesús Daniel Colmenares Oviedo <DtxdF@disroot.org>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
# * Neither the name of the copyright holder nor the names of its
#   contributors may be used to endorse or promote products derived from
#   this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

. "${AJ_CONFIG}"
. "${LIBDIR}/load"

lib_load "${LIBDIR}/log"
lib_load "${LIBDIR}/check_func"
lib_load "${LIBDIR}/jail"
lib_load "${LIBDIR}/replace"

main()
{
	local rulespec="$1"
	if lib_check_empty "${rulespec}"; then
		lib_err ${EX_USAGE} "usage: DEVICE <rulespec> ..."
	fi

	local escape_chars
	escape_chars='`"'

	printf "%s" "\"\${APPJAIL_SCRIPT}\" devfs apply -- \"\${APPJAIL_JAILNAME}\" "

	local args_list
	args_list=`lib_split_jailparams "${rulespec}"` || exit $?

	printf "%s\n" "${args_list}" | while IFS= read -r apply_arg
	do
		if ! lib_check_empty "${apply_arg}"; then
			apply_arg=`lib_escape_string "${apply_arg}" "" "${escape_chars}"`
		fi

		printf "%s " "\"${apply_arg}\""
	done
	echo

	local escape_rulespec
	escape_rulespec=`lib_escape_string "${rulespec}" "" "${escape_chars}"`

	printf "%s\n" "\"\${APPJAIL_SCRIPT}\" devfs set -- \"\${APPJAIL_JAILNAME}\" \"${escape_rulespec}\""
}

main "$@"
