#!/bin/sh
#
# Copyright (c) 2022-2023, Jesús Daniel Colmenares Oviedo <DtxdF@disroot.org>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
# * Neither the name of the copyright holder nor the names of its
#   contributors may be used to endorse or promote products derived from
#   this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

. "${AJ_CONFIG}"
. "${LIBDIR}/load"

lib_load "${LIBDIR}/check_func"
lib_load "${LIBDIR}/jail"
lib_load "${LIBDIR}/log"
lib_load "${LIBDIR}/replace"

main()
{
	local args="$1"
	if lib_check_empty "${args}"; then
		lib_err ${EX_USAGE} "usage: SET [--mark] [--column column] [--row row] parameter[=value]"
	fi
	
	# options
	local mark=0
	local opt_column=0 column=0
	local row=0

	# Arguments
	local args_list
	local total_items
	local current_index=0

	args_list=`lib_split_jailparams "${args}"` || exit $?
	total_items=`printf "%s\n" "${args_list}" | wc -l`
	
	while [ ${current_index} -lt ${total_items} ]; do 
		current_index=$((current_index+1))
		local arg=`printf "%s\n" "${args_list}" | head -${current_index} | tail -n 1`
		if lib_check_empty "${arg}"; then
			continue
		fi

		local optarg=
		case "${arg}" in
			--column|--row)
				current_index=$((current_index+1))
				if [ ${current_index} -eq ${total_items} ]; then
					main # usage
				fi

				optarg=`printf "%s\n" "${args_list}" | head -${current_index} | tail -n 1`
				if lib_check_empty "${optarg}"; then
					main # usage
				fi
				;;
		esac

		case "${arg}" in
			--mark)
				mark=1
				;;
			--column)
				opt_column=1
				column="${optarg}"
				;;
			--row)
				row="${optarg}"
				;;
			--)
				break
				;;
			--*)
				main # usage
				;;
			*)
				break
				;;
		esac
	done
	current_index=$((current_index-1))

	local escape_chars
	escape_chars='`"\'

	args_list=`lib_split_ujailparams "${args}"`

	local parameters=
	while [ ${current_index} -lt ${total_items} ]; do 
		current_index=$((current_index+1))

		local parameter=`printf "%s\n" "${args_list}" | head -${current_index} | tail -n 1`
		if lib_check_empty "${parameter}"; then
			main # usage
		fi

		parameter=`lib_escape_string "${parameter}" "" "${escape_chars}"`

		if [ -z "${parameters}" ]; then
			parameters="${parameter}"
		else
			parameters="${parameters} ${parameter}"
		fi
	done

	if lib_check_empty "${parameters}"; then
		main # usage
	fi

	row=`lib_escape_string "${row}" "" "${escape_chars}"`

	if [ ${mark} -eq 1 ]; then
		echo "appjail-config set -R1 -j \"\${APPJAIL_JAILNAME}\" -r \"${row}\" -- \"${parameters}\""
	fi

	if [ ${opt_column} -eq 1 ]; then
		column=`lib_escape_string "${column}" "" "${escape_chars}"`

		echo "appjail-config setColumn -j \"\${APPJAIL_JAILNAME}\" -c \"${column}\" -r \"${row}\" -- \"${parameters}\""
	else
		echo "appjail-config set -j \"\${APPJAIL_JAILNAME}\" -r \"${row}\" -- \"${parameters}\""
	fi
}

main "$@"
