#!/bin/sh
#
# Copyright (c) 2022-2023, Jesús Daniel Colmenares Oviedo <DtxdF@disroot.org>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
# * Neither the name of the copyright holder nor the names of its
#   contributors may be used to endorse or promote products derived from
#   this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

. "${AJ_CONFIG}"
. "${LIBDIR}/load"

lib_load "${LIBDIR}/log"
lib_load "${LIBDIR}/check_func"

main()
{
	local var="$1"
	if lib_check_empty "${var}"; then
		lib_err ${EX_USAGE} "usage: VAR [--noexpand] name[=default_value]"
	fi
	
	# options
	local noexpand=0

	# Arguments
	local args_list
	local total_items
	local current_index=0

	args_list=`lib_split_jailparams "${var}"` || exit $?
	total_items=`printf "%s\n" "${args_list}" | wc -l`
	
	while [ ${current_index} -lt ${total_items} ]; do 
		current_index=$((current_index+1))
		local arg=`printf "%s\n" "${args_list}" | head -${current_index} | tail -n 1`
		if lib_check_empty "${arg}"; then
			continue
		fi

		case "${arg}" in
			--noexpand)
				noexpand=1
				;;
			--)
				break
				;;
			--*)
				main # usage
				;;
			*)
				break
				;;
		esac
	done
	current_index=$((current_index-1))

	local escape_chars

	if [ ${noexpand} -eq 1 ]; then
		escape_chars='`"\$'
	else
		escape_chars='`"\'
	fi

	args_list=`lib_split_ujailparams "${var}"`

	var=
	while [ ${current_index} -lt ${total_items} ]; do 
		current_index=$((current_index+1))

		local _var=`printf "%s\n" "${args_list}" | head -${current_index} | tail -n 1`
		if [ -z "${var}" ]; then
			var="${_var}"
		else
			var="${var} ${_var}"
		fi
	done

	if ! lib_check_var "${var}"; then
		lib_err ${EX_DATAERR} -- "${var}: Invalid variable."
	fi

	local name=`lib_jailparam_name "${var}" "="`
	local default_value=`lib_jailparam_value "${var}" "="`

	if ! lib_check_empty "${default_value}"; then
		default_value=`lib_escape_string "${default_value}" "" "${escape_chars}"`
	fi

	printf "%s=%s\n" "${name}" "\"${default_value}\""
}

main "$@"
